import {BUTTON} from '../shared/constants';
import type {InputFrame,Team,Vec} from '../shared/protocol';
import {settings} from './settings';
export class Controls{
 keys=new Set<string>();touchButtons=0;stick={x:0,y:0};aim={x:1,y:0};seq=0;team:Team='mouse';enabled=false;private disposers:(()=>void)[]=[];
 constructor(){window.addEventListener('keydown',e=>{if(!this.enabled||e.target instanceof HTMLInputElement||e.target instanceof HTMLSelectElement)return;if(['Space','Tab','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault();this.keys.add(e.code);});window.addEventListener('keyup',e=>this.keys.delete(e.code));window.addEventListener('blur',()=>this.clear());document.addEventListener('visibilitychange',()=>this.clear());}
 clear(){this.keys.clear();this.touchButtons=0;this.stick={x:0,y:0};}
 bind(root:HTMLElement,screenToWorld:(x:number,y:number)=>Vec,self:()=>Vec|undefined){this.disposers.forEach(f=>f());this.disposers=[];const on=(target:EventTarget,name:string,fn:EventListener)=>{target.addEventListener(name,fn);this.disposers.push(()=>target.removeEventListener(name,fn));};root.querySelectorAll<HTMLElement>('[data-control]').forEach(button=>{const value=Number(button.dataset.control);on(button,'pointerdown',((e:PointerEvent)=>{e.preventDefault();button.setPointerCapture(e.pointerId);this.touchButtons|=value;button.classList.add('pressed');}) as EventListener);const up=()=>{this.touchButtons&=~value;button.classList.remove('pressed');};on(button,'pointerup',up);on(button,'pointercancel',up);on(button,'lostpointercapture',up);});const stick=root.querySelector<HTMLElement>('#joystick');if(stick){const dot=stick.querySelector<HTMLElement>('i')!;let held=false;const update=(e:PointerEvent)=>{const b=stick.getBoundingClientRect();const x=(e.clientX-b.left-b.width/2)/46,y=(e.clientY-b.top-b.height/2)/46,d=Math.max(1,Math.hypot(x,y));this.stick={x:x/d,y:y/d};dot.style.transform=`translate(${x/d*38}px,${y/d*38}px)`;};on(stick,'pointerdown',((e:PointerEvent)=>{e.preventDefault();held=true;stick.setPointerCapture(e.pointerId);update(e);}) as EventListener);on(stick,'pointermove',((e:PointerEvent)=>{if(held)update(e);}) as EventListener);const up=()=>{held=false;this.stick={x:0,y:0};dot.style.transform='';};on(stick,'pointerup',up);on(stick,'pointercancel',up);}
 const canvas=root.querySelector('canvas');if(canvas){on(canvas,'pointermove',((e:PointerEvent)=>{if(e.pointerType!=='mouse')return;const p=self();if(!p)return;const at=screenToWorld(e.clientX,e.clientY);const dx=at.x-p.x,dy=at.y-p.y,d=Math.hypot(dx,dy);if(d>.2)this.aim={x:dx/d,y:dy/d};}) as EventListener);on(canvas,'pointerdown',((e:PointerEvent)=>{if(e.pointerType!=='mouse')return;this.touchButtons|=e.button===2?BUTTON.COLANDER:BUTTON.ATTACK;}) as EventListener);on(window,'pointerup',(()=>this.touchButtons&=~(BUTTON.ATTACK|BUTTON.COLANDER)));on(canvas,'contextmenu',e=>e.preventDefault());}}
 frame(tick:number):InputFrame{let mx=this.stick.x,my=this.stick.y,buttons=this.touchButtons;if(this.enabled){mx+=(this.keys.has('KeyD')||this.keys.has('ArrowRight')?1:0)-(this.keys.has('KeyA')||this.keys.has('ArrowLeft')?1:0);my+=(this.keys.has('KeyS')||this.keys.has('ArrowDown')?1:0)-(this.keys.has('KeyW')||this.keys.has('ArrowUp')?1:0);const mapping:Record<string,number>={use:BUTTON.USE,eat:BUTTON.EAT,attack:BUTTON.ATTACK,dodge:BUTTON.DODGE,ability:BUTTON.ABILITY,trap:BUTTON.TRAP,colander:BUTTON.COLANDER,inspect:BUTTON.INSPECT};for(const [key,bit]of Object.entries(mapping))if(this.keys.has(settings.keys[key]))buttons|=bit;if(this.team==='chef'&&this.keys.has('KeyQ'))buttons|=BUTTON.TRAP;if(this.keys.has('ShiftLeft')||this.keys.has('ShiftRight')||Math.hypot(this.stick.x,this.stick.y)>.9)buttons|=BUTTON.SPRINT;if(this.keys.has('ControlLeft')||this.keys.has('ControlRight')||(Math.hypot(this.stick.x,this.stick.y)>0&&Math.hypot(this.stick.x,this.stick.y)<.5))buttons|=BUTTON.SNEAK;if(this.keys.has('Tab'))buttons|=BUTTON.PING;}else {mx=0;my=0;buttons=0;}const d=Math.max(1,Math.hypot(mx,my));if(Math.hypot(this.stick.x,this.stick.y)>.15)this.aim={x:mx/d,y:my/d};return {seq:++this.seq,tick,mx:mx/d,my:my/d,buttons,ax:this.aim.x,ay:this.aim.y};}
}
