import type {ClientMessage,ServerMessage} from '../shared/protocol';
import {WireDecoder} from '../shared/wire';
export class Connection{
 socket?:WebSocket; token='';code='';id='';name='';rtt=0;offset=0;private samples:{rtt:number;offset:number}[]=[]; private initial?:ClientMessage;private retry?:number;private tries=0;private intentional=false;private generation=0;private ping?:number;private pathCode='';private decoder=new WireDecoder();
 constructor(public onMessage:(m:ServerMessage)=>void,public onState:(s:string)=>void){}
 open(first:ClientMessage){this.close(false);this.initial=first;this.intentional=false;this.tries=0;const alphabet='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';this.pathCode=first.type==='join'?first.code:Array.from(crypto.getRandomValues(new Uint8Array(4)),n=>alphabet[n%alphabet.length]).join('');if(first.type==='join'&&first.token){this.code=first.code;this.token=first.token;}this.dial();}
 private dial(){const generation=++this.generation;this.decoder.reset();this.onState(this.tries?'Reconnecting to your kitchen…':'Waking the kitchen…');const configured=import.meta.env.VITE_WS_URL as string|undefined;const url=configured?`${configured.replace(/\/$/,'')}/${this.code||this.pathCode}`:`${location.protocol==='https:'?'wss:':'ws:'}//${location.host}/ws`;let socket:WebSocket;try{socket=new WebSocket(url);}catch{this.onState('The kitchen address is unavailable. Please try again.');return;}this.socket=socket;
 const timeout=setTimeout(()=>{if(socket.readyState!==WebSocket.OPEN)socket.close();},10000);
 socket.onopen=()=>{clearTimeout(timeout);if(generation!==this.generation)return;this.onState('Connected');this.send(this.token&&this.code?{type:'join',code:this.code,token:this.token,name:this.name}:this.initial!);this.tries=0;clearInterval(this.ping);this.ping=window.setInterval(()=>this.send({type:'time',t0:Date.now()}),4000);};
 socket.onmessage=e=>{if(generation!==this.generation)return;let m:ServerMessage|undefined;try{m=this.decoder.decode(e.data);}catch{return;}if(!m)return;if(m.type==='probe'){this.send({type:'probe',nonce:m.nonce});return;}if(m.type==='joined'){this.id=m.playerId;this.token=m.token;this.code=m.code;sessionStorage.setItem('sous-session',JSON.stringify({code:m.code,token:m.token,name:this.name}));localStorage.setItem(`sous-token-${m.code}`,m.token);}if(m.type==='pong'){const rtt=Date.now()-m.t0;this.samples.push({rtt,offset:m.serverTime-(m.t0+rtt/2)});this.samples=this.samples.slice(-5);const best=this.samples.reduce((a,b)=>a.rtt<b.rtt?a:b);this.rtt=best.rtt;this.offset=best.offset;}this.onMessage(m);};
 socket.onerror=()=>{};socket.onclose=()=>{clearTimeout(timeout);clearInterval(this.ping);if(this.intentional||generation!==this.generation)return;if(this.tries++<12){this.onState('Connection interrupted. Rejoining your kitchen…');this.retry=window.setTimeout(()=>this.dial(),Math.min(1000+this.tries*400,4000));}else this.onState('The kitchen could not be reached. Check your connection and try again.');};
 }
 send(m:ClientMessage){if(this.socket?.readyState===WebSocket.OPEN)this.socket.send(JSON.stringify(m));}
 close(clear=true){this.intentional=true;this.generation++;clearTimeout(this.retry);clearInterval(this.ping);this.socket?.close();this.socket=undefined;if(clear){this.token='';this.code='';this.id='';sessionStorage.removeItem('sous-session');}}
}
