import * as T from 'three';
import {MAP3D,COLLIDERS3D,TRAVERSALS3D,zoneAt3D,rayClear3D} from '../shared/content3d';
import type {EntityView,Snapshot,Vec,FoodId,GameEvent} from '../shared/protocol';
import {settings3d} from './settings3d';
import {settings} from './settings';
import {BistroMaterials,block,ball,tube,rod,torus,mesh,batchStatic,labelTexture,shadowTexture} from './three/materials';
import {diningTable,counter,shelf,crate,barrel,plant,cage,food,character,animateCharacter,burrowFurniture,candle,type Character} from './three/models';
import {mouseFollowPosition} from './three/camera';
import {detailedCounter,stockpot,pan,stationCanopy,pantryShelf,tiledWall,contactShade,serviceWall,serviceDoors} from './three/kitchen';
import {KitchenLife} from './three/kitchenLife';
import {RoomEnvironment} from 'three/addons/environments/RoomEnvironment.js';
import {TunnelCinema} from './three/transit';
import {SpatialKitchenAudio} from './three/audio3d';

type Actor={model:Character;last:T.Vector3;carry?:FoodId;shadow:T.Mesh;label?:T.Sprite};
type Quality='low'|'medium'|'high';
const direction=new T.Vector3(),up=new T.Vector3(0,1,0),ray=new T.Ray(),hit=new T.Vector3();
const toThree=(p:Vec)=>new T.Vector3(p.x,p.z||0,p.y);
const disposeGroup=(root:T.Object3D)=>root.traverse(n=>{if(n instanceof T.Mesh)n.geometry.dispose();});

/** Single-loop renderer. Authoritative snapshots supply every character and sensory cue. */
export class Scene3D {
 ready=false;target?:Vec;renderer!:T.WebGLRenderer;scene=new T.Scene();camera=new T.PerspectiveCamera(85,1,.01,80);
 private materials!:BistroMaterials;private tunnel!:TunnelCinema;private audio!:SpatialKitchenAudio;private host!:HTMLElement;private veil!:HTMLDivElement;private resizeObserver?:ResizeObserver;private dead=false;private lost=false;private yaw=0;private pitch=0;private lookSet=false;private width=1;private height=1;private elapsed=0;private quality:Quality='medium';private settingQuality='';private scale=.85;private frameMs=16;private frames=0;private renderMs=0;private adjustments=0;private eye=.07;private fov=85;private transit=false;private exitFade=0;private cameraInitialized=false;
 private kitchenLife!:KitchenLife;private environment?:T.WebGLRenderTarget;
 private actors=new Map<string,Actor>();private guests=new Map<string,{group:T.Group;last:T.Vector3;phase:number}>();private pickups=new Map<string,T.Group>();private traps=new Map<string,T.Group>();private keys=new Map<string,T.Group>();private rooms:{group:T.Group;x:number;y:number;r:number;id:string}[]=[];private dynamic=new T.Group();private effects=new T.Group();private viewScene=new T.Scene();private viewCamera=new T.PerspectiveCamera(65,1,.005,2);private paws=new T.Group();private snout=new T.Group();private whiskers:T.Mesh[]=[];private heldHand=new T.Group();private heldMouse?:Character;private viewFood=new T.Group();private viewFoodId?:FoodId;private viewBuilt=false;private marker!:T.Mesh;private ripples:{mesh:T.Mesh;born:number;radius:number;kind:string}[]=[];private eventIds=new Set<number>();private scent=new T.Group();private scentKey='';private shadowMap!:T.Texture;private shadowMaterial!:T.MeshBasicMaterial;private moon!:T.DirectionalLight;private localLamp!:T.PointLight;private lights:T.PointLight[]=[];private colliders:T.Box3[]=[];private lastSelf?:Vec;private speed=0;private tremor=0;private extraTextures:T.Texture[]=[];private extraMaterials:T.Material[]=[];private minimap?:HTMLCanvasElement;private mapPaintAt=0;private lastDrawAt=0;private drawCalls=0;private triangles=0;private tunnelDrawCalls=0;private tunnelTriangles=0;

 async init(host:HTMLElement){this.host=host;await document.fonts.ready;if(this.dead)return;const canvas=document.createElement('canvas');const gl=canvas.getContext('webgl2',{alpha:false,antialias:false,powerPreference:'high-performance'});if(!gl)throw new Error('This kitchen needs WebGL2. Enable hardware acceleration or open the 2D kitchen.');this.renderer=new T.WebGLRenderer({canvas,context:gl,antialias:false,powerPreference:'high-performance'});this.renderer.outputColorSpace=T.SRGBColorSpace;this.renderer.toneMapping=T.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.08;this.renderer.shadowMap.type=T.PCFSoftShadowMap;this.renderer.autoClear=false;this.renderer.info.autoReset=false;canvas.style.cssText='display:block;width:100%;height:100%;touch-action:none';canvas.setAttribute('aria-label','Cartoon 3D view of the Rusty Ladle bistro');host.append(canvas);this.veil=document.createElement('div');this.veil.style.cssText='position:absolute;inset:0;pointer-events:none;z-index:1;transition:background 180ms;background:transparent';host.append(this.veil);this.materials=new BistroMaterials();this.shadowMap=shadowTexture();this.shadowMaterial=new T.MeshBasicMaterial({map:this.shadowMap,transparent:true,depthWrite:false,opacity:.7});this.extraMaterials.push(this.shadowMaterial);this.scene.background=new T.Color('#3d383a');this.scene.fog=new T.Fog('#554845',22,62);this.scene.add(new T.HemisphereLight('#ffdfb0','#554653',1.2));this.moon=new T.DirectionalLight('#ffd6a6',1.8);this.moon.position.set(8,16,-6);this.moon.target.position.set(15,0,12);this.moon.castShadow=true;this.moon.shadow.mapSize.set(1024,1024);Object.assign(this.moon.shadow.camera,{left:-18,right:18,top:18,bottom:-18,near:.1,far:45});this.moon.shadow.bias=-.0003;this.moon.shadow.normalBias=.02;this.scene.add(this.moon,this.moon.target);this.localLamp=new T.PointLight('#ffc47f',.2,7,1.4);this.scene.add(this.localLamp);const pmrem=new T.PMREMGenerator(this.renderer),env=new RoomEnvironment();this.environment=pmrem.fromScene(env,.04);this.scene.environment=this.environment.texture;this.scene.environmentIntensity=.65;env.dispose();pmrem.dispose();this.scene.add(this.dynamic,this.effects);this.buildMap();this.kitchenLife=new KitchenLife(this.materials,this.shadowMaterial);this.dynamic.add(this.kitchenLife.root);this.buildViewmodel();this.tunnel=new TunnelCinema(this.materials);this.audio=new SpatialKitchenAudio();this.applyQuality();this.resizeObserver=new ResizeObserver(()=>this.resize());this.resizeObserver.observe(host);this.resize();canvas.addEventListener('webglcontextlost',this.contextLost);canvas.addEventListener('webglcontextrestored',this.contextRestored);this.ready=true;}
 private contextLost=(event:Event)=>{event.preventDefault();this.lost=true;this.veil.style.background='#271d32';this.veil.textContent='The kitchen is catching its breath. Restoring the view…';this.veil.style.display='grid';this.veil.style.placeItems='center';this.veil.style.color='#f5d7a6';this.veil.style.font='700 16px Nunito';};
 private contextRestored=()=>{this.lost=false;this.veil.textContent='';this.veil.style.background='transparent';this.scale=.6;this.quality='low';this.renderer.shadowMap.enabled=false;this.resize();this.materials.all.forEach(m=>{m.needsUpdate=true;if(m.map)m.map.needsUpdate=true;});};
 setLook(yaw:number,pitch:number){if(Number.isFinite(yaw))this.yaw=yaw;if(Number.isFinite(pitch))this.pitch=T.MathUtils.clamp(pitch,-80*Math.PI/180,85*Math.PI/180);this.lookSet=true;}
 metrics(){return {renderer:'three',kitchen:this.kitchenLife?.metrics(this.transit),quality:this.quality,renderScale:this.scale,drawCalls:this.drawCalls,triangles:this.triangles,tunnelDrawCalls:this.tunnelDrawCalls,tunnelTriangles:this.tunnelTriangles,frameMs:this.frameMs,renderMs:this.renderMs,frames:this.frames,textures:this.renderer?.info.memory.textures||0,geometries:this.renderer?.info.memory.geometries||0,contextLost:this.lost,mouseEye:this.eye,cameraPosition:{x:this.camera.position.x,y:this.camera.position.z,z:this.camera.position.y},fov:this.camera.fov,transit:this.transit,cameraView:settings3d.comfortCamera?'follow':'first-person',selfVisible:[...this.actors.values()].some(a=>a.model.root.userData.isSelf&&a.model.root.visible)};}
 private resize(){if(!this.renderer||this.dead)return;const bounds=this.host.getBoundingClientRect();this.width=Math.max(1,bounds.width);this.height=Math.max(1,bounds.height);const maxRatio=this.quality==='high'?1.5:1;this.renderer.setPixelRatio(Math.min(devicePixelRatio,maxRatio)*this.scale);this.renderer.setSize(this.width,this.height,false);this.camera.aspect=this.viewCamera.aspect=this.width/this.height;this.camera.updateProjectionMatrix();this.viewCamera.updateProjectionMatrix();}
 private applyQuality(){const requested=settings3d.quality;this.settingQuality=requested;this.quality=requested==='auto'?(matchMedia('(pointer: coarse)').matches?'low':'medium'):requested;this.scale=this.quality==='low'?.65:this.quality==='medium'?.85:1;this.renderer.shadowMap.enabled=this.quality==='high';this.moon.castShadow=this.quality==='high';this.lights.forEach(l=>{l.visible=this.quality==='high';l.intensity=(l.userData.intensity as number);});this.localLamp.visible=this.quality==='high';this.materials.applyBudget(this.scene,this.quality!=='high');this.materials.applyBudget(this.viewScene,this.quality!=='high');this.materials.applyBudget(this.tunnel.scene,this.quality!=='high');this.resize();}
 private surfaceLabel(parent:T.Group,label:string,x:number,y:number,z:number,w:number,h:number,yaw=0){const texture=labelTexture(label);this.extraTextures.push(texture);const material=new T.MeshBasicMaterial({map:texture,side:T.DoubleSide});this.extraMaterials.push(material);const plane=mesh(parent,new T.PlaneGeometry(w,h),material,x,y,z);plane.rotation.y=yaw;plane.castShadow=false;return plane;}
 private buildMap(){const m=this.materials;this.colliders=COLLIDERS3D.filter(c=>!c.cover).map(c=>new T.Box3(new T.Vector3(c.x,c.z,c.y),new T.Vector3(c.x+c.w,c.z+c.h,c.y+c.d)));const worldRaw=new T.Group();
  for(const z of MAP3D.zones){const raw=new T.Group();const burrow=z.id==='burrow',dining=z.id==='dining',kitchen=z.id==='kitchen',foyer=z.id==='foyer';const floor=m.get(`floor-${z.id}`,burrow?'#94724c':dining?'#9b7457':kitchen?'#e0c8a3':foyer?'#94756b':'#6c8781',dining||burrow?'wood':kitchen?'paris-tile':'tile');floor.map!.repeat.set(z.w/1.6,z.h/1.6);block(raw,floor,z.x+z.w/2,-.05,z.y+z.h/2,z.w,.1,z.h);const ceiling=m.get(`ceiling-${z.id}`,burrow?'#76614d':'#b5aa91','plaster');block(raw,ceiling,z.x+z.w/2,burrow?.65:2.83,z.y+z.h/2,z.w,.06,z.h);if(burrow){for(const side of [-1,1])block(raw,m.get('burrow-earth','#79614b','brick'),z.x+z.w/2,.31,z.y+z.h/2+side*z.h/2,z.w,.65,.08);for(const side of [-1,1])block(raw,m.get('burrow-earth','#79614b','brick'),z.x+z.w/2+side*z.w/2,.31,z.y+z.h/2,.08,.65,z.h);for(let x=z.x+.3;x<z.x+z.w;x+=.45){const beam=tube(raw,m.wood,x,.32,z.y+.07,.016,.62);beam.rotation.z=.1;}for(let x=z.x+.5;x<z.x+z.w-.2;x+=.8){candle(raw,m,x,0,z.y+.35,.55);const bed=burrowFurniture(m,'nest');bed.position.set(x,0,z.y+z.h-.4);raw.add(bed);}for(const x of [z.x+1,z.x+3,z.x+6,z.x+8]){const furniture=burrowFurniture(m,'table');furniture.position.set(x,0,z.y+1);raw.add(furniture);}this.surfaceLabel(raw,'THE COLONY',22,.28,29.8,.7,.16);}
   else{for(let x=z.x+1;x<z.x+z.w;x+=3.6){block(raw,m.wood,x,2.72,z.y+z.h/2,.09,.14,z.h);for(let y=z.y+2;y<z.y+z.h;y+=4.8){tube(raw,m.iron,x,2.48,y,.012,.45);const shade=mesh(raw,new T.CylinderGeometry(.08,.27,.13,12,1,true),m.copper,x,2.21,y);const lamp=tube(raw,m.glow('ceiling-light','#ffe2a4',1.1),x,2.155,y,.22,.009);}}if(dining){for(let x=2;x<23;x+=4.5){block(raw,m.wood,x,1.53,.2,1.4,1.9,.08);block(raw,m.glow('night-window','#5d8291',.25),x,1.54,.247,1.23,1.68,.015);for(const dx of [-.4,0,.4])block(raw,m.brass,x+dx,1.54,.265,.025,1.65,.024);block(raw,m.wood,x,1.5,.27,1.27,.035,.026);for(const dx of [-.76,.76]){for(let i=0;i<5;i++)tube(raw,m.wine,x+dx+i*.025,.99,.32,.028,1.86);}candle(raw,m,x, .6,.38,.85);}this.surfaceLabel(raw,'THE RUSTY LADLE',11,2.15,.27,3.7,.6);}if(kitchen){for(let x=3;x<22;x+=2.6){rod(raw,m.copper,new T.Vector3(x,2.24,14.25),new T.Vector3(x,2.24,25.4),.025);for(let y=15;y<25;y+=3){torus(raw,m.brass,x,2.18,y,.045,.008);const pan=tube(raw,m.iron,x,1.97,y,.16,.035);pan.rotation.x=Math.PI/2;block(raw,m.wood,x,2.18,y,.038,.24,.034);}}this.surfaceLabel(raw,'YES, CHEF.',5,2.5,25.7,1.7,.35,Math.PI);for(const x of [7,14,21]){const rack=serviceWall(m);rack.position.set(x,0,25.6);raw.add(rack);}const doors=serviceDoors(m);doors.position.set(2.5,0,25.76);raw.add(doors);}if(foyer){const fireplace=new T.Group();block(fireplace,m.get('hearth','#75564b','brick'),0,.5,0,1.8,1,.3);block(fireplace,m.black,0,.36,.17,1.15,.6,.02);for(let i=0;i<5;i++){ball(fireplace,m.glow('ember','#e78b43',.9),-.4+i*.2,.22,.2,.09,.15,.04);}block(fireplace,m.oak,0,1.025,.02,1.96,.08,.48);fireplace.position.set(38,0,.45);raw.add(fireplace);this.surfaceLabel(raw,'DINNER IS A TEAM SPORT',34,2.1,.26,3,.48);}if(!dining){for(let x=z.x+1;x<z.x+z.w;x+=2.7){block(raw,m.get('wall-tile','#afc0ac','tile'),x,1.05,z.y+z.h-.03,1.9,.55,.025);}}}
   const group=batchStatic(raw,true);this.scene.add(group);this.rooms.push({group,x:z.x+z.w/2,y:z.y+z.h/2,r:Math.hypot(z.w,z.h)/2,id:z.id});
  }
  for(const o of MAP3D.objects){if(o.kind==='wall'){const zone=zoneAt3D(o.x-.2,o.y-.2);const mat=m.get(`wall-${zone?.id||'dining'}`,zone?.id==='pantry'?'#70877b':zone?.id==='kitchen'?'#e5d2b0':'#b39175',zone?.id==='kitchen'?'tile':'plaster');tiledWall(worldRaw,mat,o.x,(o.z||0)+o.height/2,o.y,o.w||.2,o.height,o.d);if((o.z||0)<.2){block(worldRaw,m.wood,o.x,.065,o.y,(o.w||.2)+.017,.13,o.d+.017);block(worldRaw,m.oak,o.x,.139,o.y,(o.w||.2)+.022,.018,o.d+.022);block(worldRaw,m.wood,o.x,1.02,o.y,(o.w||.2)+.02,.065,o.d+.02);}continue;}let model:T.Group|undefined;const w=o.w||1.6,d=o.d||.6;switch(o.kind){case'table':model=diningTable(m);break;case'counter':case'prep':case'stove':case'pass':model=detailedCounter(m,o.kind,w,d);break;case'soup':model=stockpot(m,.145,.28,true);break;case'sink':model=detailedCounter(m,'sink',w,d);break;case'rafter':model=new T.Group();rod(model,m.copper,new T.Vector3(-w/2,.06,0),new T.Vector3(w/2,.06,0),.06);for(let k=-w/2+.5;k<w/2;k+=1.8)torus(model,m.brass,k,.06,0,.065,.012).rotation.y=Math.PI/2;break;case'shelf':model=pantryShelf(m,w,d,o.height);break;case'barrel':model=barrel(m);break;case'plant':model=plant(m);break;case'nest':case'cauldron':model=burrowFurniture(m,o.kind);break;case'stash':model=crate(m,.32,.23,.16);{const c=food(m,'cheese');c.position.set(.03,.12,0);model.add(c);}break;case'bar':model=counter(m,'bar',w,d);break;case'stool':model=new T.Group();for(let i=0;i<4;i++){const a=Math.PI/4+i*Math.PI/2;rod(model,m.wood,new T.Vector3(Math.cos(a)*.18,0,Math.sin(a)*.18),new T.Vector3(Math.cos(a)*.14,.7,Math.sin(a)*.14),.025);}tube(model,m.wine,0,.72,0,.22,.075);torus(model,m.brass,0,.25,0,.16,.012).rotation.x=Math.PI/2;break;case'coat':model=new T.Group();tube(model,m.wood,0,1,0,.025,2);for(let i=0;i<4;i++){const a=i*Math.PI/2;rod(model,m.wood,new T.Vector3(0,.11,0),new T.Vector3(Math.cos(a)*.35,.04,Math.sin(a)*.35),.025);rod(model,m.brass,new T.Vector3(0,1.65,0),new T.Vector3(Math.cos(a)*.18,1.81,Math.sin(a)*.18),.01);}break;case'host':model=counter(m,'host',.8,.5);break;case'flour':model=new T.Group();ball(model,m.linen,0,.2,0,.2,.22,.15);torus(model,m.wood,0,.37,0,.07,.014).rotation.x=Math.PI/2;break;case'pan':model=pan(m,.17);break;default:break;}if(model){model.position.set(o.x,o.kind==='pass'?0:o.z||0,o.y);worldRaw.add(model);if(['prep','stove','sink','pass','shelf','barrel'].includes(o.kind))contactShade(worldRaw,m,o.x,.003,o.y,w+.4,d+.4);if(o.kind==='stove'||o.kind==='prep'){const canopy=stationCanopy(m,w,d,o.kind==='prep');canopy.position.set(o.x,0,o.y);worldRaw.add(canopy);}}}
  for(const c of MAP3D.cages){const model=cage(m);model.position.copy(toThree(c));worldRaw.add(model);}
  for(const h of MAP3D.holes){const arch=new T.Group();arch.position.copy(toThree(h));arch.rotation.y=Math.PI/2-h.exitYaw;const radius=h.wide?.12:.085;const shape=new T.Shape();shape.moveTo(-radius,0);shape.lineTo(-radius,radius);shape.absarc(0,radius,radius,Math.PI,0,true);shape.lineTo(radius,0);shape.closePath();const black=new T.MeshBasicMaterial({color:'#181620',side:T.DoubleSide});this.extraMaterials.push(black);mesh(arch,new T.ShapeGeometry(shape,12),black,0,0,-.035);const outline=new T.CurvePath<T.Vector3>();outline.add(new T.LineCurve3(new T.Vector3(-radius,0,0),new T.Vector3(-radius,radius,0)));for(let i=0;i<12;i++){const a=Math.PI-i*Math.PI/12,b=Math.PI-(i+1)*Math.PI/12;rod(arch,m.oak,new T.Vector3(Math.cos(a)*radius,radius+Math.sin(a)*radius,0),new T.Vector3(Math.cos(b)*radius,radius+Math.sin(b)*radius,0),.013);}block(arch,m.oak,-radius,radius/2,0,.025,radius,.035);block(arch,m.oak,radius,radius/2,0,.025,radius,.035);block(arch,m.get('hole-mat','#a67d57','fabric'),0,.001,.08,radius*2.7,.003,.13);ball(arch,m.glow('hole-light','#f5bc6f',.55),0,radius*.7,-.033,radius*.88,radius*.95,.001);this.surfaceLabel(arch,h.id,0,radius*2+.045,.02,.085,.03);worldRaw.add(arch);}
  for(const t of TRAVERSALS3D){const p=t.from;const glow=m.get('chalk-scuffs','#e1cfac');for(let i=0;i<3;i++){const stripe=block(worldRaw,glow,p.x-.035+i*.035,(p.z||0)+.009,p.y,.012,.004,.055);stripe.rotation.y=.3;}}
  // Mouse-scale landmarks: crumbs, a fallen fork, sacks and a thread trail home.
  for(let i=0;i<130;i++){const x=1+(i*13.61)%42,y=1+(i*7.19)%24;const size=.007+(i%4)*.003;ball(worldRaw,m.cheese,x,.006,y,size,.007,size*.7);}const fork=new T.Group();block(fork,m.steel,0,.012,0,.015,.01,.22);block(fork,m.steel,0,.012,-.12,.055,.009,.047);for(let i=0;i<4;i++)block(fork,m.steel,-.022+i*.015,.012,-.16,.005,.008,.045);fork.position.set(8,0,7);fork.rotation.y=.5;worldRaw.add(fork);for(let i=0;i<45;i++){const x=17.3+i*.18,z=28.1+Math.sin(i*.3)*.17;rod(worldRaw,m.wine,new T.Vector3(x,.008,z),new T.Vector3(x+.18,.008,28.1+Math.sin((i+1)*.3)*.17),.0015);}
  const roomProps=new Map<string,T.Group>();for(const child of [...worldRaw.children]){const zone=zoneAt3D(child.position.x,child.position.z);const id=zone?.id||'walls';let group=roomProps.get(id);if(!group){group=new T.Group();roomProps.set(id,group);}group.add(child);}for(const[id,raw]of roomProps){const group=batchStatic(raw,true);this.scene.add(group);const z=MAP3D.zones.find(z=>z.id===id);if(z)this.rooms.push({group,x:z.x+z.w/2,y:z.y+z.h/2,r:Math.hypot(z.w,z.h)/2,id:z.id});}for(const [x,y,z,color,power,range]of [[9,2,7,'#ffc888',22,14],[17,1.8,20,'#ffc08d',16,12],[32,2,19,'#9cc6b6',17,14],[37,.7,1,'#f4b474',8,8],[22,.28,28.9,'#ffc36e',1.5,5]] as const){const l=new T.PointLight(color,power,range,2);l.position.set(x,y,z);l.userData.intensity=power;this.scene.add(l);this.lights.push(l);}
  const markerMaterial=new T.MeshBasicMaterial({color:'#ffe1a1',transparent:true,opacity:.8,side:T.DoubleSide,depthWrite:false});this.extraMaterials.push(markerMaterial);this.marker=new T.Mesh(new T.TorusGeometry(.105,.006,5,24),markerMaterial);this.marker.rotation.x=-Math.PI/2;this.effects.add(this.marker,this.scent);
 }

 private buildViewmodel(){const m=this.materials;this.viewScene.add(new T.HemisphereLight('#ffe0b9','#786274',2.8));const key=new T.DirectionalLight('#f7d4a3',1.5);key.position.set(-1,2,1);this.viewScene.add(key);for(const s of [-1,1]){const paw=new T.Group();ball(paw,m.get('view-fur','#b29a85','fabric'),0,0,0,.018,.025,.024);for(let i=0;i<3;i++)ball(paw,m.pink,-.012+i*.012,.006,-.013,.006,.009,.01);paw.position.set(s*.12,-.09,-.21);paw.rotation.z=-s*.4;this.paws.add(paw);}ball(this.snout,m.get('snout-fur','#a58b77','fabric'),0,-.117,-.19,.045,.018,.04);ball(this.snout,m.pink,0,-.104,-.216,.017,.009,.011);for(const s of [-1,1])for(let i=0;i<4;i++){const whisker=rod(this.snout,m.get('whiskers','#d5b9a3'),new T.Vector3(s*.02,-.106,-.215),new T.Vector3(s*(.075+i*.012),-.091+i*.007,-.25-i*.014),.00035);this.whiskers.push(whisker);}this.viewFood.position.set(0,-.106,-.24);this.viewFood.scale.setScalar(.75);this.paws.scale.setScalar(.6);this.paws.position.y=-.027;this.snout.scale.setScalar(.65);this.snout.position.y=-.027;this.viewScene.add(this.paws,this.snout,this.viewFood);for(const s of [-1,1]){ball(this.heldHand,m.skin,s*.075,-.095,-.22,.055,.025,.07);for(let i=0;i<3;i++)ball(this.heldHand,m.skin,s*.04,-.061+i*.023,-.24-i*.005,.016,.021,.015);}this.viewScene.add(this.heldHand);this.heldHand.visible=false;this.viewBuilt=true;}
 private actor(e:EntityView){let a=this.actors.get(e.id);if(a)return a;const model=character(this.materials,e.team,e.classId,[...e.id].reduce((n,c)=>n+c.charCodeAt(0),0)%6);const shadow=new T.Mesh(new T.PlaneGeometry(1,1),this.shadowMaterial);shadow.rotation.x=-Math.PI/2;shadow.scale.setScalar(e.team==='mouse'?.18:.8);this.materials.applyBudget(model.root,this.quality!=='high');this.dynamic.add(model.root,shadow);a={model,last:toThree(e),shadow};this.actors.set(e.id,a);return a;}
 private actorsDraw(s:Snapshot,entities:EntityView[],self:EntityView,dt:number){const visible=new Set(entities.filter(e=>!e.transit&&e.state!=='transit').map(e=>e.id));for(const [id,a]of this.actors)if(!visible.has(id)){this.dynamic.remove(a.model.root,a.shadow);disposeGroup(a.model.root);this.actors.delete(id);}for(const e of entities){if(!visible.has(e.id))continue;const a=this.actor(e),at=toThree(e),distance=at.distanceTo(this.camera.position);const own=e.id===self.id;const show=(!own||(e.team==='chef'&&!settings3d.chefFirstPerson)||(e.team==='mouse'&&settings3d.comfortCamera))&&distance<24&&(e.y>=27)===(self.y>=27)&&(!e.hidden||own);a.model.root.userData.isSelf=own;a.model.root.visible=show;a.shadow.visible=show;a.shadow.position.set(e.x,(e.z||0)+.003,e.y);const speed=Math.min(8,at.distanceTo(a.last)/Math.max(.001,dt));a.last.copy(at);a.model.root.position.copy(at);if(!show)continue;animateCharacter(a.model,e,s.time,speed,settings.reduced);if(a.carry!==e.carry){a.model.carry.clear();a.carry=e.carry;if(e.carry){a.model.carry.add(food(this.materials,e.carry));this.materials.applyBudget(a.model.carry,this.quality!=='high');}}if(e.state==='caged')a.model.root.position.y+=.025;if(e.state==='held')a.model.root.position.y=e.z||0;}
  const activeGuests=new Set(s.guests.map(g=>g.id));for(const [id,g]of this.guests)if(!activeGuests.has(id)){this.dynamic.remove(g.group);disposeGroup(g.group);this.guests.delete(id);}for(let i=0;i<s.guests.length;i++){const e=s.guests[i];let g=this.guests.get(e.id);if(!g){const char=character(this.materials,'guest','head',i);char.legs.forEach(l=>{l.rotation.x=-1.1;});char.arms.forEach(a=>a.rotation.x=-.65);char.root.position.y=-.35;const container=new T.Group();container.add(char.root);const merged=batchStatic(container);this.materials.applyBudget(merged,this.quality!=='high');this.dynamic.add(merged);g={group:merged,last:toThree(e),phase:i};this.guests.set(e.id,g);}const group=g.group;const near=Math.hypot(e.x-self.x,e.y-self.y);group.visible=(e.y>=27)===(self.y>=27)&&near<(this.quality==='low'?9:14);if(!group.visible)continue;group.position.set(e.x,(e.z||0)+(e.state==='panicked'?.34:0),e.y);group.rotation.y=Math.PI/2-e.angle;group.rotation.z=settings.reduced?0:/startle|panic|reaction/.test(e.state)?Math.sin(s.time*6+i)*.06:Math.sin(s.time*.6+i)*.006;if(e.state==='fleeing'){group.position.y+=Math.abs(Math.sin(s.time*9+i))*.03;}}
 }
 private itemsDraw(s:Snapshot,self:EntityView){const active=new Set(s.pickups.filter(p=>p.available).map(p=>p.id));for(const [id,g]of this.pickups)if(!active.has(id)){this.dynamic.remove(g);disposeGroup(g);this.pickups.delete(id);}for(const p of s.pickups){if(!p.available)continue;let g=this.pickups.get(p.id);if(!g){g=food(this.materials,p.food);this.materials.applyBudget(g,this.quality!=='high');this.pickups.set(p.id,g);this.dynamic.add(g);}g.position.set(p.x,(p.z||0)+(!settings.reduced?Math.sin(s.time*2+p.x)*.002+.002:0),p.y);g.visible=(p.y>=27)===(self.y>=27)&&Math.hypot(p.x-self.x,p.y-self.y)<12;g.rotation.y=p.x*.3;}
  const keys=new Set(s.cages.filter(c=>c.keyDropped).map(c=>c.id));for(const [id,g]of this.keys)if(!keys.has(id)){this.dynamic.remove(g);disposeGroup(g);this.keys.delete(id);}for(const c of s.cages){if(!c.keyDropped)continue;let g=this.keys.get(c.id);if(!g){g=new T.Group();const mat=this.materials.glow('key-gold','#d2dc8f',.45);torus(g,mat,0,.02,0,.018,.003);block(g,mat,.035,.02,0,.045,.007,.007);block(g,mat,.049,.014,0,.006,.014,.007);this.materials.applyBudget(g,this.quality!=='high');this.keys.set(c.id,g);this.dynamic.add(g);}g.position.copy(toThree(c.keyDropped));g.position.y+=.016;g.rotation.y=s.time*.7;}
  const traps=new Set(s.traps.map(t=>t.id));for(const [id,g]of this.traps)if(!traps.has(id)){this.dynamic.remove(g);disposeGroup(g);this.traps.delete(id);}for(const t of s.traps){let g=this.traps.get(t.id);if(!g){g=new T.Group();block(g,this.materials.oak,0,.006,0,.16,.012,.1);torus(g,this.materials.steel,0,.021,0,.045,.003).rotation.x=-Math.PI/2;block(g,this.materials.cheese,0,.026,0,.025,.02,.024);this.materials.applyBudget(g,this.quality!=='high');this.dynamic.add(g);this.traps.set(t.id,g);}g.position.copy(toThree(t));g.visible=Math.hypot(t.x-self.x,t.y-self.y)<18;}
 }
 private sensoryDraw(s:Snapshot,self:EntityView,dt:number){for(const e of s.events){if(this.eventIds.has(e.id))continue;this.eventIds.add(e.id);if(s.time-e.time>1.2||Math.hypot(e.x-self.x,e.y-self.y)>(e.radius||8))continue;if(/tremor|ripple|rustle|noise|alert|ping|capture|rescue|deliver/.test(e.kind)){const mat=new T.MeshBasicMaterial({color:/tremor|alert|capture/.test(e.kind)?'#e59f70':'#e3cf96',transparent:true,opacity:.5,depthWrite:false,side:T.DoubleSide});const ring=new T.Mesh(new T.RingGeometry(.97,1,48),mat);ring.rotation.x=-Math.PI/2;ring.position.set(e.x,(e.z||0)+.007,e.y);this.effects.add(ring);this.ripples.push({mesh:ring,born:s.time,radius:e.kind==='tremor'?2.8:1.4,kind:e.kind});}if(e.kind==='tremor'&&self.team==='mouse')this.tremor=Math.max(this.tremor,1-Math.hypot(e.x-self.x,e.y-self.y)/12);}
  if(this.eventIds.size>500)this.eventIds=new Set(s.events.map(e=>e.id));for(const p of this.ripples){const age=s.time-p.born;p.mesh.scale.setScalar(Math.max(.03,age*p.radius));(p.mesh.material as T.MeshBasicMaterial).opacity=Math.max(0,.5-age*.35);}this.ripples=this.ripples.filter(p=>{if(s.time-p.born<1.5)return true;this.effects.remove(p.mesh);p.mesh.geometry.dispose();(p.mesh.material as T.Material).dispose();return false;});this.tremor*=Math.exp(-dt*9);
  this.marker.visible=!!this.target&&settings3d.outlines;if(this.target){this.marker.position.copy(toThree(this.target));this.marker.position.y+=.012;this.marker.scale.setScalar(1+Math.sin(s.time*3)*.1);}
  const sensing=self.team==='mouse'&&(self.cooldowns?.senseUntil||0)>s.time;this.scent.visible=sensing;if(sensing){const targets:Vec[]=[...s.pickups.filter(p=>p.available&&Math.hypot(p.x-self.x,p.y-self.y)<18),...s.cages.flatMap(c=>c.keyDropped?[c.keyDropped]:[]),...s.entities.filter(e=>e.team===self.team&&e.id!==self.id&&!e.transit)];const hole=MAP3D.holes.reduce((a,b)=>Math.hypot(a.x-self.x,a.y-self.y)<Math.hypot(b.x-self.x,b.y-self.y)?a:b);targets.push(hole);const key=`${Math.round(self.x*2)},${Math.round(self.y*2)}-${targets.length}`;if(key!==this.scentKey){this.scentKey=key;disposeGroup(this.scent);this.scent.clear();const geo=new T.SphereGeometry(.007,5,4),mat=this.materials.glow('scent','#b5d4a1',.8);for(const at of targets.slice(0,12)){for(let i=1;i<=10;i++){const f=i/10;const x=self.x+(at.x-self.x)*f,z=self.y+(at.y-self.y)*f,y=(self.z||0)+((at.z||0)-(self.z||0))*f+.04+Math.sin(f*Math.PI)*.09;mesh(this.scent,geo,mat,x,y,z);}}}this.scent.rotation.y=0;}else this.scentKey='';
 }
 private cameraDraw(s:Snapshot,self:EntityView,dt:number){if(!this.lookSet){this.yaw=self.angle;this.pitch=self.pitch||0;}const mouse=self.team==='mouse';const at=toThree(self);if(this.lastSelf){this.speed=T.MathUtils.lerp(this.speed,Math.min(7,Math.hypot(self.x-this.lastSelf.x,self.y-this.lastSelf.y)/Math.max(.001,dt)),.25);}this.lastSelf={x:self.x,y:self.y,z:self.z};const sneaking=mouse&&this.speed>.1&&this.speed<1.4;this.eye=T.MathUtils.lerp(this.eye,mouse?(sneaking?.05:.07):1.65,1-Math.exp(-dt*10));const held=mouse&&self.state==='held';const targetHeight=this.eye;const origin=at.clone().add(new T.Vector3(0,targetHeight,0));const bob=settings3d.bob&&!settings.reduced&&this.speed>0&&this.speed<3?Math.sin(s.time*(mouse?17:7))*(mouse?.0015:.008):0;origin.y+=bob;if(!settings.reduced&&settings3d.shake>0&&mouse){origin.y+=Math.sin(s.time*50)*this.tremor*.005*settings3d.shake;origin.x+=Math.cos(s.time*43)*this.tremor*.003*settings3d.shake;}
  direction.set(Math.cos(this.yaw)*Math.cos(this.pitch),Math.sin(this.pitch),Math.sin(this.yaw)*Math.cos(this.pitch));let desired=origin.clone();const shoulder=!mouse&&!settings3d.chefFirstPerson,comfort=mouse&&settings3d.comfortCamera;if(comfort)desired=mouseFollowPosition(origin,this.yaw,this.pitch,this.colliders);if(shoulder){const distance=1.6;const side=shoulder?.5*settings3d.shoulder:0;desired.addScaledVector(new T.Vector3(Math.cos(this.yaw),0,Math.sin(this.yaw)),-distance).addScaledVector(new T.Vector3(-Math.sin(this.yaw),0,Math.cos(this.yaw)),side);desired.y+=shoulder?.35:.15;const delta=desired.clone().sub(origin),length=delta.length();ray.set(origin,delta.normalize());let max=length;for(const box of this.colliders){const expanded=box.clone().expandByScalar(shoulder?.08:.012);if(expanded.containsPoint(origin))continue;const cross=ray.intersectBox(expanded,hit);if(cross){const d=cross.distanceTo(origin)-.02;if(d<max)max=Math.max(.015,d);}}desired.copy(origin).addScaledVector(delta,max);}
  if(self.state==='caged'&&!comfort)desired.y=Math.max(.055,(self.z||0)+.07);this.camera.position.copy(desired);const look=origin.clone().addScaledVector(direction,comfort?.08:shoulder?5:2);if(shoulder||comfort)this.camera.lookAt(look);else this.camera.lookAt(desired.clone().add(direction));if(held&&!settings.reduced)this.camera.rotateZ(Math.sin(s.time*8)*.014*settings3d.shake);const sensing=mouse&&(self.cooldowns?.senseUntil||0)>s.time;const sprint=this.speed>3.3;const fov=settings3d.fov+(mouse&&!settings.reduced?(self.buff==='dash'?10:sprint?6:0):0)-(sensing?5:0);this.fov=T.MathUtils.lerp(this.fov,T.MathUtils.clamp(fov,65,110),1-Math.exp(-dt*5));if(Math.abs(this.camera.fov-this.fov)>.02){this.camera.fov=this.fov;this.camera.updateProjectionMatrix();}this.localLamp.position.copy(this.camera.position);this.localLamp.intensity=zoneAt3D(self.x,self.y)?.id==='burrow'?.22:mouse?.08:.18;this.cameraInitialized=true;
  this.paws.visible=mouse&&!settings3d.comfortCamera&&!held;this.snout.visible=mouse&&!settings3d.comfortCamera;this.heldHand.visible=held&&!comfort;const action=self.action?.kind;for(let i=0;i<this.paws.children.length;i++){const paw=this.paws.children[i];paw.position.y=-.09+(settings.reduced?0:Math.sin(s.time*15+i*Math.PI)*.002*Math.min(1,this.speed))+(action?.includes('eat')?.018:action?.includes('pickup')?.014:0);paw.rotation.x=action?Math.sin(s.time*8)*.15:0;}if(this.viewFoodId!==self.carry){disposeGroup(this.viewFood);this.viewFood.clear();this.viewFoodId=self.carry;if(self.carry){this.viewFood.add(food(this.materials,self.carry));this.materials.applyBudget(this.viewFood,this.quality!=='high');}}this.viewFood.visible=mouse&&!!self.carry&&!settings3d.comfortCamera&&!held;this.viewFood.rotation.x=action==='eat'?Math.sin(s.time*11)*.11:0;this.viewFood.position.y=-.106+(settings.reduced?0:Math.sin(s.time*8)*.002);
  const nearby=this.colliders.some(b=>b.distanceToPoint(this.camera.position)<.15);for(let i=0;i<this.whiskers.length;i++){const whisker=this.whiskers[i];whisker.visible=mouse;whisker.scale.y=nearby?.7:1;}this.snout.position.y=held?-.018:-.027;
  const danger=mouse?Math.min(...s.entities.filter(e=>e.team==='chef').map(e=>Math.hypot(e.x-self.x,e.y-self.y)),99):99;const edge=settings3d.vignette&&sprint?.32:0;const dangerAlpha=danger<6?(1-danger/6)*.22:0;this.veil.style.boxShadow=`inset 0 0 ${Math.round(this.height*.25)}px ${Math.round(this.height*.05)}px rgba(${dangerAlpha>0?'137,50,51':'24,20,31'},${Math.max(edge,dangerAlpha)})`;this.veil.style.filter='';if(sensing)this.veil.style.background='rgba(24,36,39,.09)';else if(this.exitFade<=0)this.veil.style.background='transparent';
 }
 private mapDraw(s:Snapshot,self:EntityView){if(!this.minimap)return;this.minimap.hidden=!(settings3d.minimap||self.team==='chef');if(this.minimap.hidden||s.time-this.mapPaintAt<.15)return;this.mapPaintAt=s.time;const c=this.minimap.getContext('2d')!;c.clearRect(0,0,220,156);for(const zone of MAP3D.zones){c.fillStyle=zone.id==='burrow'?'#886e4e':'#766c63';c.fillRect(zone.x*4.8+4,zone.y*4.8+4,zone.w*4.8,zone.h*4.8);}for(const h of MAP3D.holes){c.fillStyle=s.plugs[h.id]>s.time?'#a2786b':'#e9c580';c.beginPath();c.arc(h.x*4.8+4,h.y*4.8+4,2,0,Math.PI*2);c.fill();}for(const cage of s.cages){c.fillStyle=cage.occupant?'#dfaa82':'#cab8a5';c.fillRect(cage.x*4.8+2,cage.y*4.8+2,4,4);}for(const e of s.entities.filter(e=>e.team===self.team&&!e.transit)){c.fillStyle=e.id===self.id?'#fff0ca':'#94c6ab';c.beginPath();c.arc(e.x*4.8+4,e.y*4.8+4,e.id===self.id?3:2,0,Math.PI*2);c.fill();}}
 screenToWorld(x:number,y:number):Vec{if(!this.renderer)return {x:0,y:0,z:0};const rect=this.renderer.domElement.getBoundingClientRect();const raycaster=new T.Raycaster();raycaster.setFromCamera(new T.Vector2((x-rect.left)/rect.width*2-1,-(y-rect.top)/rect.height*2+1),this.camera);const ground=new T.Plane(new T.Vector3(0,1,0),0),point=new T.Vector3();if(raycaster.ray.intersectPlane(ground,point)&&point.distanceTo(this.camera.position)<20)return {x:point.x,y:point.z,z:point.y};point.copy(this.camera.position).addScaledVector(raycaster.ray.direction,6);return {x:point.x,y:point.z,z:point.y};}
 draw(s:Snapshot,entities:EntityView[],self:EntityView|undefined,dt:number){if(!this.ready||this.dead||this.lost||document.hidden||!self)return;const began=performance.now();dt=Math.min(.1,Math.max(.001,dt));this.elapsed+=dt;this.frames++;const actualFrame=this.lastDrawAt?Math.min(1000,began-this.lastDrawAt):dt*1000;this.lastDrawAt=began;this.frameMs=this.frameMs*.98+actualFrame*.02;if(this.settingQuality!==settings3d.quality)this.applyQuality();if(this.elapsed>3&&settings3d.quality==='auto'&&this.frames%120===0){if(this.frameMs>27&&this.scale>.5){this.scale=Math.max(.5,this.scale-.1);this.renderer.shadowMap.enabled=false;this.resize();this.adjustments++;}else if(this.frameMs<17&&this.scale<.85){this.scale=Math.min(.85,this.scale+.05);this.resize();}}
  this.renderer.info.reset();const inTransit=!!self.transit;const reduced=settings.reduced||settings3d.skipTransit;if(inTransit){if(this.minimap)this.minimap.hidden=true;if(!this.transit){this.tunnel.reset();this.transit=true;}const frame=this.tunnel.draw(self.transit!,s.time,dt,reduced,this.width/this.height);if(reduced){this.veil.style.background='rgba(22,19,29,.96)';this.veil.textContent='Following the warm light…';this.veil.style.display='grid';this.veil.style.placeItems='center';this.veil.style.font='700 15px Nunito';this.veil.style.color='#e6c497';}else{this.veil.textContent='';this.veil.style.background='transparent';}this.renderer.clear();this.renderer.render(frame.scene,frame.camera);this.tunnelDrawCalls=this.renderer.info.render.calls;this.tunnelTriangles=this.renderer.info.render.triangles;this.audio.update(self,this.yaw,this.pitch,s.time,s.events,0);}
  else{if(this.transit){this.transit=false;this.exitFade=.35;this.veil.textContent='';this.veil.style.background='rgba(229,205,158,.25)';this.cameraInitialized=false;}this.exitFade=Math.max(0,this.exitFade-dt);if(this.exitFade>0)this.veil.style.background=`rgba(229,205,158,${this.exitFade*.6})`;this.cameraDraw(s,self,dt);const room=zoneAt3D(self.x,self.y);for(const entry of this.rooms)entry.group.visible=(entry.id==='burrow')===(room?.id==='burrow')&&Math.hypot(entry.x-self.x,entry.y-self.y)<entry.r+9;this.actorsDraw(s,entities,self,dt);this.kitchenLife.update(s.time,self,settings.reduced);this.itemsDraw(s,self);this.sensoryDraw(s,self,dt);this.mapDraw(s,self);this.audio.update(self,this.yaw,this.pitch,s.time,s.events,this.speed);this.renderer.clear();this.renderer.render(this.scene,this.camera);if(self.team==='mouse'&&!settings3d.comfortCamera){this.renderer.clearDepth();this.renderer.render(this.viewScene,this.viewCamera);}}
  this.drawCalls=this.renderer.info.render.calls;this.triangles=this.renderer.info.render.triangles;this.renderMs=this.renderMs*.95+(performance.now()-began)*.05;
 }
 destroy(){if(this.dead)return;this.dead=true;this.ready=false;this.resizeObserver?.disconnect();this.audio?.dispose();this.renderer?.domElement.removeEventListener('webglcontextlost',this.contextLost);this.renderer?.domElement.removeEventListener('webglcontextrestored',this.contextRestored);disposeGroup(this.scene);disposeGroup(this.viewScene);this.tunnel?.dispose();this.kitchenLife?.dispose();this.environment?.dispose();this.materials?.dispose();this.shadowMap?.dispose();this.extraMaterials.forEach(m=>m.dispose());this.extraTextures.forEach(t=>t.dispose());this.renderer?.dispose();this.renderer?.domElement.remove();this.veil?.remove();this.minimap?.remove();}
}

