import {createWorld,stepWorld,visibleTo} from '../shared/sim';
import {MAP,isWalkable} from '../shared/content';
import {BUTTON,DT} from '../shared/constants';
import type {World,Team,Vec,InputFrame,Snapshot,Player} from '../shared/protocol';
export class Training{
 world:World;step=0;target?:Vec;title='';description='';control='';done=false;private origin:Vec={x:0,y:0};private startTime=0;private moved=0;private sneaked=0;private eventStart=0;
 constructor(public team:Team,public changed:()=>void){this.world=createWorld([{id:'trainee',name:'You',team,classId:team==='mouse'?'scout':'head',ready:true,bot:false,connected:true},{id:'partner',name:team==='mouse'?'Clove':'Pip',team:'mouse',classId:'rescuer',ready:true,bot:true,connected:true},{id:'coach',name:'Bram',team:'chef',classId:'head',ready:true,bot:true,connected:true}],{duration:3600,bots:false,difficulty:'easy'},42);this.world.guests=[];this.world.nextOrder=99999;this.world.pickups=[];this.setup();}
 get self(){return this.world.players[0];}
 get total(){return this.team==='mouse'?8:6;}
 safe(at:Vec,team:Team,range=1.1){for(let r=range;r<4;r+=.25)for(let a=0;a<Math.PI*2;a+=Math.PI/8){const p={x:at.x+Math.cos(a)*r,y:at.y+Math.sin(a)*r};if(isWalkable(p.x,p.y,team,'floor',team==='mouse'?.28:.5))return p;}return at;}
 place(p:Player,at:Vec,layer:Player['layer']='floor'){Object.assign(p,{x:at.x,y:at.y},{layer,action:undefined,lastButtons:0,hidden:undefined,invulnerableUntil:0});}
 private setup(){const p=this.self,w=this.world;this.eventStart=w.nextId;this.startTime=w.time;this.moved=0;this.sneaked=0;w.result=undefined;w.rating=70;w.lockdown=0;p.action=undefined;p.lastButtons=0;p.cooldowns={};const coach=w.players.find(p=>p.id==='coach')!,ally=w.players.find(p=>p.id==='partner')!;this.place(coach,{x:50,y:6});this.place(ally,{x:35,y:44},'tunnel');const hole=MAP.holes.find(h=>h.room==='pantry')||MAP.holes[0];const pass=MAP.objects.find(o=>o.kind==='pass')!;const cage=w.cages[0];
 if(this.team==='mouse'){
  if(this.step===0){this.place(p,{x:35,y:44},'tunnel');this.origin={x:p.x,y:p.y};this.target={x:p.x+3,y:p.y};this.title='Small feet. Big plans.';this.description='Move around with WASD or the left stick. Then sneak with Ctrl + move, or a gentle stick tilt.';this.control='MOVE + SNEAK';}
  if(this.step===1){const pickup=MAP.pickups.find(x=>x.food==='cheese'&&MAP.holes.every(h=>Math.hypot(h.x-x.x,h.y-x.y)>2))||MAP.pickups[0];w.pickups=[{...pickup,id:'lesson-cheese',food:'cheese',available:true,respawnAt:9999}];this.place(p,this.safe(pickup,'mouse',.8));this.target=pickup;this.title='Borrow a little cheese.';this.description='Stand by the glowing cheese. Stop moving and hold Use (E) until the circle fills.';this.control='USE';}
  if(this.step===2){this.target=undefined;this.title='A snack with a superpower.';this.description='Hold Eat (F) to eat your cheese. Dash makes you faster. Food can be eaten, delivered, or used to spoil a dish.';this.control='EAT';}
  if(this.step===3){p.carry='tomato';this.place(p,this.safe(hole,'mouse',.6));this.target=hole;this.title='Take the secret route.';this.description='Here is a tomato for the colony. Hold Use (E) at this mouse hole to enter the tunnels. Chefs cannot follow.';this.control='USE';}
  if(this.step===4){this.place(p,{x:MAP.stash.x+1.4,y:MAP.stash.y},'tunnel');this.target=MAP.stash;this.title='A very good delivery.';this.description='Hold Use (E) beside the Colony Stash. Food deliveries fill the Heist meter. Reach 100 to win.';this.control='USE';}
  if(this.step===5){const soup=MAP.objects.find(o=>o.kind==='soup')!;this.place(p,this.safe(soup,'mouse',1.2));this.place(coach,this.safe(soup,'chef',1.7));this.target=soup;this.title='Turn up the heat.';this.description='Hold Use (E) beside the soup pot. Spilling it hurts nearby chefs’ Composure. At zero, they drop mice and cage keys.';this.control='USE';}
  if(this.step===6){this.place(p,this.safe(cage,'mouse',1.2));this.place(ally,cage);ally.state='caged';ally.cageId=cage.id;ally.stateUntil=w.time+3600;cage.occupant=ally.id;cage.keyOwner=coach.id;cage.keyDropped={x:p.x+.2,y:p.y};cage.keyUntil=w.time+3600;this.target=cage.keyDropped;this.title='Never leave a mouse behind.';this.description='Clove is caged. Hold Use (E) to collect the glowing key beside you. In a match, keys drop when a keyholder loses Composure.';this.control='USE';}
  if(this.step===7){this.target=cage;this.title='The best heist is a team heist.';this.description='Hold Use (E) beside Clove’s cage to unlock it. Keep a teammate free: three seconds with every mouse caught ends the match.';this.control='USE';}
 }else{
  if(this.step===0||this.step===1){this.place(p,this.safe(pass,'chef',1.5));w.orders=[{id:'lesson-order',tableId:'guest-0',stage:'ready',elapsed:0,age:0,readyAt:w.time,cold:false,vip:false,...(this.step===1?{tamper:'garlic' as const}:{})}];this.target=pass;this.title=this.step===0?'Service, please.':'Something smells suspicious.';this.description=this.step===0?'At the Pass, stop moving and hold Use (E) to garnish and send this dish. Fast service restores the restaurant’s Rating.':'This dish has been tampered with. Hold Inspect (I) at the Pass to remake it safely before sending.';this.control=this.step===0?'USE':'INSPECT';}
  if(this.step===2){w.orders=[];this.place(p,{x:14,y:27});this.place(ally,{x:14.9,y:27});ally.state='free';p.angle=0;this.target=ally;this.title='Caught with crumbs.';this.description='Face Pip and tap Grab (left click or the Grab button). On touch, a slight stick tilt aims. Get close: your reach is just over one tile.';this.control='GRAB';}
  if(this.step===3){this.place(p,this.safe(cage,'chef',1.4));ally.state='held';ally.heldBy=p.id;p.holding=ally.id;this.target=cage;this.title='A short stay in the pantry.';this.description='You are carrying Pip. Hold Use (E) at the cage to lock it. Mice auto-release after 40 seconds, and teammates can rescue them sooner.';this.control='USE';}
  if(this.step===4){p.holding=undefined;ally.state='free';ally.heldBy=undefined;ally.cageId=undefined;cage.occupant=undefined;cage.keyOwner=undefined;this.place(ally,{x:35,y:44},'tunnel');this.place(p,{x:14,y:27});this.target={x:p.x,y:p.y};this.title='Leave a little surprise.';this.description='Hold Trap (T or Q) for one second to place a snap trap. It arms after a moment and briefly stops a mouse that steps on it.';this.control='TRAP';}
  if(this.step===5){const hide=MAP.hides.find(h=>{const q=this.safe(h,'chef',.8);return Math.hypot(q.x-h.x,q.y-h.y)<=1.5;})||MAP.hides[0];this.place(p,this.safe(hide,'chef',.8));this.target=hide;this.title='Check the quiet corners.';this.description='Hold Use (E) beside this hiding spot to search it. Keep the Rating above zero and the Heist below 100 until service ends to win.';this.control='USE';}
 }
 this.changed();}
 update(input:InputFrame){if(this.done)return;const p=this.self;const prev={x:p.x,y:p.y};stepWorld(this.world,new Map([[p.id,input]]),DT);this.world.result=undefined;this.world.rating=Math.max(40,this.world.rating);this.world.lockdown=0;if(this.team==='mouse'&&this.step===6){const c=this.world.cages[0];if(!c.keyCarrier)c.keyUntil=this.world.time+30;}if(this.team==='mouse'&&this.step===7)this.world.cages[0].keyUntil=this.world.time+30;this.moved+=Math.hypot(p.x-prev.x,p.y-prev.y);if(input.buttons&BUTTON.SNEAK)this.sneaked+=Math.hypot(p.x-prev.x,p.y-prev.y);const events=this.world.events.filter(e=>e.id>=this.eventStart);const event=(kind:string)=>events.some(e=>e.kind===kind);let complete=false;if(this.team==='mouse')complete=[this.moved>1.5&&this.sneaked>.3,event('pickup'),event('eat'),p.layer==='tunnel',event('deliver'),event('soup'),!!this.world.cages[0].keyCarrier,p.stats.rescues>0][this.step];else complete=[event('send'),event('inspect'),!!p.holding,event('cage'),event('trap'),event('search')][this.step];if(complete){this.step++;if(this.step>=this.total){this.done=true;localStorage.setItem(`sous-trained-${this.team}`,'yes');this.changed();}else this.setup();}}
 snapshot():Snapshot{const w=this.world,p=this.self;return {type:'snap',tick:w.tick,time:w.time,duration:w.duration,ackSeq:p.ackSeq,selfId:p.id,entities:w.players.filter(e=>visibleTo(w,p,e)),pickups:w.pickups,cages:w.cages,traps:w.traps,guests:w.guests,orders:w.orders,events:w.events,heist:w.heist,rating:w.rating,lockdown:w.lockdown,plugs:w.plugs};}
}
