import {BUTTON} from '../shared/constants';
import {MAP3D} from '../shared/content3d';
import type {EntityView,Snapshot,Team} from '../shared/protocol';
import {icon,escapeHTML as esc} from './icons';
import {settings3d,saveSettings3d,toggleMouseCamera,type Settings3D} from './settings3d';
import {keys3d,key3d,Controls3D} from './input3d';
import {settings,saveSettings} from './settings';
import './style3d.css';
import './presentation.css';

const keyAction:Record<string,string>={aim:'attack',grab:'attack',toss:'colander',listen:'ear'};
export const keyLabel=(action:string)=>key3d(action).replace(/^Key/,'').replace(/^Digit/,'').replace(/^(Control|Shift|Alt|Meta)(Left|Right)$/,'$1').replace('Control','Ctrl');
const action=(name:string,bit:number,ico:string,_key:string,primary=false)=>{const action=name.toLowerCase(),binding=keyAction[action]||action;return `<button class="action-button ${primary?'main-action':''}" data-control="${bit}" aria-label="${name}" data-action="${action}" data-key-action="${binding}">${icon(ico)}<span>${name}</span><kbd>${esc(keyLabel(binding))}</kbd><i class="cooldown"></i></button>`;};
export function install3dHud(root:HTMLElement,team:Team,choose:(exit:string)=>void,controls:Controls3D){
 root.querySelector('.game-screen')?.classList.add('game3d');
 root.querySelector('.action-buttons')!.innerHTML=action('Use',BUTTON.USE,'grab','E',true)+(team==='mouse'?action('Eat',BUTTON.EAT,'cheese','F')+action('Aim',BUTTON.ATTACK,'tomato','Q')+action('Jump',BUTTON.JUMP,'arrow','Space')+action('Sense',BUTTON.SENSE,'eye','C')+action('Ability',BUTTON.ABILITY,'star','R')+action('Dodge',BUTTON.DODGE,'bolt','X')+action('Trap',BUTTON.TRAP,'trap','T'):action('Grab',BUTTON.ATTACK,'grab','Click',true)+action('Toss',BUTTON.COLANDER,'bowl','V')+action('Inspect',BUTTON.INSPECT,'eye','I')+action('Trap',BUTTON.TRAP,'trap','T')+action('Ability',BUTTON.ABILITY,'star','R')+action('Peek',BUTTON.PEEK,'eye','B')+action('Listen',BUTTON.EAR,'sound','N'));
 root.querySelector('.hud')!.insertAdjacentHTML('beforeend',`<span id="crosshair" aria-hidden="true"></span><div id="stealth-eye" class="stealth-eye">${icon('eye')}<span>Hidden</span></div><div class="sense-instructions" id="look-hint">Click the view to look around · Esc releases the mouse</div><div class="navigation-buttons">${team==='mouse'?'<button id="camera3d-toggle" class="icon-button camera-toggle" aria-label="Switch to first-person view" aria-pressed="true" data-key-action="view">'+icon('mouse')+'<span>View</span><kbd>'+esc(keyLabel('view'))+'</kbd></button>':''}<button id="map3d-toggle" class="icon-button" aria-label="Toggle map" data-key-action="map">${icon('map')}<kbd>${esc(keyLabel('map'))}</kbd></button>${action('Ping',BUTTON.PING,'flag','Tab')}</div><div id="map3d-panel" class="map3d-panel" hidden></div><div id="transit-hud" class="transit-hud" hidden><span class="eyebrow">THE TUNNEL FORK</span><h2>Where to, little paws?</h2><div id="transit-choices" class="transit-choices"></div><p id="transit-status"></p></div>`);
 root.querySelector('#camera3d-toggle')?.addEventListener('click',toggleMouseCamera);
 root.querySelector('#map3d-toggle')!.addEventListener('click',()=>controls.mapOpen=!controls.mapOpen);
 root.querySelector('#transit-choices')!.addEventListener('click',e=>{const b=(e.target as HTMLElement).closest<HTMLButtonElement>('[data-exit]');if(b&&!b.disabled)choose(b.dataset.exit!);});
 controls.mapOpen=settings3d.minimap;
 root.querySelector<HTMLElement>('#look-hint')!.dataset.until=String(performance.now()+6000);
}
export function update3dHud(root:HTMLElement,s:Snapshot,self:EntityView,controls:Controls3D){
 root.style.setProperty('--action-opacity',String(settings3d.buttonOpacity));
 const movement=root.querySelector('.keyboard-move');if(movement)movement.innerHTML=['forward','left','back','right'].map(a=>'<kbd>'+esc(keyLabel(a))+'</kbd>').join('')+'<small>Move · '+esc(keyLabel('sprint'))+' sprint</small>';
 const carry=root.querySelector<HTMLElement>('#carry-info');if(carry)carry.hidden=!self.carry&&!self.holding;
 const context=root.querySelector<HTMLElement>('#context-prompt');if(context){context.style.setProperty('--progress',self.action?String(Math.min(1,self.action.progress/self.action.duration)*100)+'%':'0%');}
 const map=root.querySelector('#map3d-toggle');map?.setAttribute('aria-expanded',String(controls.mapOpen));
 root.querySelectorAll<HTMLElement>('[data-key-action]').forEach(b=>{const k=b.querySelector('kbd');if(k)k.textContent=keyLabel(b.dataset.keyAction!);});
 const camera=root.querySelector<HTMLButtonElement>('#camera3d-toggle');if(camera){camera.setAttribute('aria-pressed',String(settings3d.comfortCamera));camera.setAttribute('aria-label',settings3d.comfortCamera?'Switch to first-person view':'Show whole mouse in follow view');camera.title=(settings3d.comfortCamera?'Follow view':'First-person view')+' · '+key3d('view').replace('Key','');camera.querySelector('span')!.textContent=settings3d.comfortCamera?'Follow':'Eyes';}
 const cross=root.querySelector<HTMLElement>('#crosshair');cross?.classList.toggle('aiming',controls.aiming);if(cross)cross.hidden=self.state==='transit'||self.team==='mouse'&&settings3d.comfortCamera&&!controls.aiming;
 const hint=root.querySelector<HTMLElement>('#look-hint');if(hint)hint.hidden=performance.now()>Number(hint.dataset.until)||!!document.pointerLockElement||matchMedia('(pointer:coarse)').matches||self.state==='transit';
 const eye=root.querySelector<HTMLElement>('#stealth-eye');if(eye){eye.hidden=self.team!=='mouse'||self.state==='transit';const exposure=self.exposure??(self.hidden||self.layer==='tunnel'?0:.6);eye.dataset.exposure=exposure<.2?'closed':exposure<.7?'half':'open';eye.querySelector('span')!.textContent=exposure<.2?'Hidden':exposure<.7?'In cover':'Exposed';}
 const panel=root.querySelector<HTMLElement>('#map3d-panel');if(panel){panel.hidden=!controls.mapOpen;if(controls.mapOpen){const dots=[...MAP3D.holes.map(h=>`<circle cx="${h.x}" cy="${h.y}" r=".28" fill="${s.plugs[h.id]>s.time?'#cc7770':'#f6ce86'}"/>`),...s.cages.map(c=>`<rect x="${c.x-.3}" y="${c.y-.3}" width=".6" height=".6" fill="${c.occupant?'#e8897c':'#fff0ce'}"/>`),...s.entities.filter(e=>e.team===self.team&&e.state!=='transit').map(e=>`<circle cx="${e.x}" cy="${e.y}" r="${e.id===self.id?0.42:0.25}" fill="${e.id===self.id?'#ffffff':'#9bd8c2'}"/>`)];panel.innerHTML=`<span>YOUR TEAM · ROUTES</span><svg viewBox="0 0 44 30" role="img" aria-label="Known holes, cages and teammates">${MAP3D.zones.map(z=>`<rect x="${z.x}" y="${z.y}" width="${z.w}" height="${z.h}" rx=".3" fill="#695454" stroke="#c1a88a" stroke-width=".08"/>`).join('')}${dots.join('')}</svg>`;}}
 const box=root.querySelector<HTMLElement>('#transit-hud');if(!box)return;const t=self.transit;box.hidden=!t;if(!t)return;const selecting=s.time<t.depart;box.classList.toggle('running',!selecting);box.querySelector('h2')!.textContent=selecting?'Where to, little paws?':t.rerouted?'A blocked exit. Taking a detour.':'Follow the warm light.';
 const choices=box.querySelector<HTMLElement>('#transit-choices')!;const signature=t.choices.join(',')+t.exit+selecting+Object.keys(s.plugs).filter(k=>s.plugs[k]>s.time).join(',');if(choices.dataset.signature!==signature){choices.dataset.signature=signature;choices.innerHTML=selecting?t.choices.map(id=>{const h=MAP3D.holes.find(h=>h.id===id),z=MAP3D.zones.find(z=>z.id===h?.room),blocked=s.plugs[id]>s.time;return `<button data-exit="${esc(id)}" class="button ${id===t.exit?'primary':'secondary'}" ${blocked?'disabled':''}>${icon('map')}<span>${esc(z?.name||h?.room||id)}<small>${blocked?'Blocked':id===t.exit?'Default route':id}</small></span></button>`;}).join(''):'';}
 box.querySelector('#transit-status')!.textContent=selecting?`Default route leaves in ${Math.max(0,t.depart-s.time).toFixed(1)}s`:`${Math.max(0,t.arrive-s.time).toFixed(1)}s to fresh air${settings3d.skipTransit?' · gentle transit':''}`;
}
export function settings3dHTML(){
 const check=(key:keyof Settings3D,label:string)=>`<label class="setting-toggle"><span>${label}</span><input type="checkbox" data-setting3d="${key}" ${settings3d[key]?'checked':''}><i></i></label>`;
 const slider=(key:keyof Settings3D,label:string,min:number,max:number,step:number)=>`<label class="setting-range">${label}<output>${settings3d[key]}</output><input type="range" data-setting3d="${key}" value="${settings3d[key]}" min="${min}" max="${max}" step="${step}"></label>`;
 return `<div class="comfort-settings"><h3>Your view of the bistro</h3><div class="settings-grid"><section><label class="field">Picture quality<select data-setting3d="quality">${['auto','low','medium','high'].map(q=>`<option value="${q}" ${settings3d.quality===q?'selected':''}>${q==='auto'?'Automatic':q[0].toUpperCase()+q.slice(1)}</option>`).join('')}</select></label>${slider('fov','Field of view',70,100,1)}${slider('sensitivity','Look sensitivity',.2,3,.1)}${slider('shake','Camera shake',0,1,.05)}${check('bob','Gentle head bob')}${check('invertY','Invert vertical look')}${check('comfortCamera','See your whole mouse ('+keyLabel('view')+' toggles view)')}${check('chefFirstPerson','Chef first-person camera')}<label class="field">Chef shoulder<select data-setting3d="shoulder"><option value="1" ${settings3d.shoulder===1?'selected':''}>Right</option><option value="-1" ${settings3d.shoulder===-1?'selected':''}>Left</option></select></label></section><section>${check('skipTransit','Gentle tunnel transit')}${check('reduceFlicker','Reduce flickering light')}${check('vignette','Sprint edge shading')}${check('outlines','Highlight interactables')}${check('minimap','Mouse minimap by default')}${check('autoSprint','Sprint at stick edge')}${check('toggleSense','Toggle Sense instead of hold')}${check('toggleUse','Toggle Use instead of hold')}${check('gyro','Gyroscope look assist')}${slider('buttonOpacity','Button opacity',.35,1,.05)}${slider('deadzone','Stick deadzone',.05,.35,.01)}</section></div><details class="remap"><summary>3D keyboard controls</summary><div class="remap-grid">${Object.keys(keys3d).map(k=>`<label>${esc(k)}<button class="key-remap" data-remap3d="${k}">${esc(key3d(k).replace('Key',''))}</button></label>`).join('')}</div></details></div>`;
}
export function bindSettings3d(root:HTMLElement){
 root.querySelectorAll<HTMLInputElement|HTMLSelectElement>('[data-setting3d]').forEach(el=>el.addEventListener('input',async()=>{const key=el.dataset.setting3d as keyof Settings3D;let value:unknown=el instanceof HTMLInputElement&&el.type==='checkbox'?el.checked:el.type==='range'||key==='shoulder'?Number(el.value):el.value;
 if(key==='gyro'&&value){const api=(window.DeviceOrientationEvent??{}) as unknown as {requestPermission?:()=>Promise<string>};if(api.requestPermission){try{value=await api.requestPermission()==='granted';}catch{value=false;}if(el instanceof HTMLInputElement)el.checked=!!value;}}
 Object.assign(settings3d,{[key]:value});const output=el.parentElement?.querySelector('output');if(output)output.textContent=String(value);saveSettings3d();}));
 root.querySelectorAll<HTMLElement>('[data-remap3d]').forEach(el=>el.onclick=()=>{el.textContent='Press a key';const listener=(e:KeyboardEvent)=>{e.preventDefault();e.stopPropagation();if(e.code!=='Escape')settings.keys['3d-'+el.dataset.remap3d!]=e.code;saveSettings();el.textContent=key3d(el.dataset.remap3d!).replace('Key','');window.removeEventListener('keydown',listener,true);};window.addEventListener('keydown',listener,true);});
}
