import {test,expect} from '@playwright/test';
import {mkdirSync,writeFileSync} from 'node:fs';
for(const size of [{width:844,height:390},{width:932,height:430},{width:1024,height:768},{width:1440,height:900}])test(`3D layout ${size.width}x${size.height}`,async({browser,baseURL})=>{
 const c=await browser.newContext({viewport:size,hasTouch:size.width<1000});const p=await c.newPage(),errors:string[]=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(baseURL+'?r=3d');await p.locator('#training').click();await p.locator('#learn-mouse').click();await expect(p.locator('canvas[data-engine]')).toBeVisible();await expect(p.locator('#training-card')).toBeVisible();await p.waitForTimeout(500);const bounds=await p.evaluate(()=>({w:document.documentElement.scrollWidth,h:document.documentElement.scrollHeight,iw:innerWidth,ih:innerHeight}));expect(bounds.w).toBeLessThanOrEqual(bounds.iw);expect(bounds.h).toBeLessThanOrEqual(bounds.ih);const targets=await p.locator('.action-buttons button').evaluateAll(els=>els.map(e=>({w:e.getBoundingClientRect().width,h:e.getBoundingClientRect().height})));expect(targets.every(t=>t.w>=(size.width<1000?56:44)&&t.h>=(size.width<1000?56:44))).toBe(true);mkdirSync('work/browser3d',{recursive:true});await p.screenshot({path:`work/browser3d/layout-${size.width}.png`});expect(errors).toEqual([]);await c.close();
});
test('3D comfort settings persist and affect the camera',async({page,baseURL})=>{
 await page.goto(baseURL+'?r=3d');await page.locator('#training').click();await page.locator('#learn-mouse').click();await expect(page.locator('canvas[data-engine]')).toBeVisible();await page.locator('#pause').click();await page.locator('#open-settings').click();const range=page.locator('[data-setting3d=fov]');await range.evaluate((e:HTMLInputElement)=>{e.value='95';e.dispatchEvent(new Event('input',{bubbles:true}));});for(const key of ['comfortCamera','skipTransit'])await page.locator(`[data-setting3d=${key}]`).check();for(const key of ['bob','vignette'])await page.locator(`[data-setting3d=${key}]`).uncheck();await page.locator('[data-setting3d=shake]').evaluate((e:HTMLInputElement)=>{e.value='0';e.dispatchEvent(new Event('input',{bubbles:true}));});await page.locator('#modal-close').click();await expect.poll(()=>page.evaluate(()=>(window as any).__sous3d.metrics().fov)).toBeGreaterThan(94);await expect.poll(()=>page.evaluate(()=>(window as any).__sous3d.metrics().cameraPosition.z)).toBeGreaterThan(.15);expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('sous-settings-3d')!))).toMatchObject({fov:95,comfortCamera:true,skipTransit:true,bob:false,vignette:false,shake:0});
 const loss=await page.evaluate(()=>{const g=(document.querySelector('canvas[data-engine]') as HTMLCanvasElement).getContext('webgl2');const e=g?.getExtension('WEBGL_lose_context');(window as any).__lostGL=e;e?.loseContext();return !!e;});if(loss){await expect.poll(()=>page.evaluate(()=>(window as any).__sous3d.metrics().contextLost)).toBe(true);await page.evaluate(()=>{(window as any).__lostGL?.restoreContext();});await expect.poll(()=>page.evaluate(()=>(window as any).__sous3d.metrics().contextLost),{timeout:10000}).toBe(false);}
});
