import {describe,it,expect} from 'vitest';
import {Rooms,type Peer} from '../server/rooms';
import {WireDecoder} from '../shared/wire';
import {BUTTON,DT} from '../shared/constants';
import {MAP3D} from '../shared/content3d';
import type {InputFrame,ServerMessage,Snapshot} from '../shared/protocol';

function peer(id:string){const messages:ServerMessage[]=[],raw:string[]=[];const decoder=new WireDecoder();return{id,messages,raw,send:(s:string)=>{raw.push(s);const m=decoder.decode(s);if(m)messages.push(m);},close:()=>{}};}
function fixture(mode:'3d'|'2d'='3d'){
  const rooms=new Rooms();let now=100000,seq=0;rooms.now=()=>now;const a=peer('a'),b=peer('b');
  const send=(p:Peer,m:unknown)=>rooms.receive(p,JSON.stringify(m));
  send(a,{type:'create',name:'Mouse',team:'mouse',mode:mode==='3d'?'3d':undefined});const joined=a.messages.find(m=>m.type==='joined');if(joined?.type!=='joined')throw new Error('Missing join');
  send(b,{type:'join',code:joined.code,name:'Chef'});send(b,{type:'setTeam',team:'chef'});send(a,{type:'host',options:{bots:false}});send(a,{type:'ready',value:true});send(b,{type:'ready',value:true});send(a,{type:'start'});send(a,{type:'skip'});send(b,{type:'skip'});rooms.tick();
  const room=rooms.rooms.get(joined.code)!;room.world!.guests=[];room.world!.nextOrder=999;
  const tick=(buttons?:number)=>{now+=1000*DT;if(buttons!==undefined){const m=room.world!.players.find(p=>p.id===joined.playerId)!;send(a,{type:'input',frame:{seq:++seq,tick:room.world!.tick,mx:0,my:0,buttons,ax:m.x+1,ay:m.y,yaw:0,pitch:0} satisfies InputFrame});}rooms.tick();};
  return{rooms,room,a,b,send,joined,tick,advance:(ms:number)=>now+=ms};
}
const latest=(p:ReturnType<typeof peer>)=>p.messages.filter((m):m is Snapshot=>m.type==='snap').at(-1)!;
function enter(f:ReturnType<typeof fixture>){const m=f.room.world!.players.find(p=>p.id===f.joined.playerId)!,h=MAP3D.holes.find(h=>h.id==='H5')!;Object.assign(m,{x:h.x,y:h.y,z:h.z??0});for(let i=0;i<19;i++)f.tick(BUTTON.USE);expect(m.state).toBe('transit');return m;}

describe('v3 room protocol regression',()=>{
  it('inherits mode on join and synchronizes metre snapshots for separate peers',()=>{const f=fixture();f.tick();expect(f.room.options.mode).toBe('3d');expect(f.b.messages.filter(m=>m.type==='lobby').at(-1)).toMatchObject({options:{mode:'3d'}});const a=latest(f.a),b=latest(f.b);expect(a.mode).toBe('3d');expect(b.mode).toBe('3d');expect(a.tick).toBe(b.tick);expect(a.time).toBe(b.time);expect(a.entities.find(p=>p.id===a.selfId)).toMatchObject({mode:'3d',z:0});});
  it('only admits the new button bits for rooms created in3d',()=>{for(const mode of ['3d','2d'] as const){const f=fixture(mode),id=f.joined.playerId;f.send(f.a,{type:'input',frame:{seq:9,tick:1,mx:0,my:0,buttons:BUTTON.JUMP|BUTTON.SENSE|BUTTON.EAR,ax:1,ay:1,yaw:0,pitch:0}});expect(f.room.inputs.has(id)).toBe(mode==='3d');f.send(f.a,{type:'input',frame:{seq:10,tick:1,mx:0,my:0,buttons:32768,ax:1,ay:1}});expect(f.room.inputs.get(id)?.seq).not.toBe(10);}});
  it('sends private fork timings only to mouse peers and strips them from every chef wire snapshot',()=>{const f=fixture(),m=enter(f);m.revealUntil=100;for(let i=0;i<6;i++)f.tick(0);expect(latest(f.a).entities.find(p=>p.id===m.id)?.transit).toMatchObject({entry:'H5'});const entered=m.transit!.entered;const snapshots=f.b.messages.filter((s):s is Snapshot=>s.type==='snap'&&s.time>=entered);expect(snapshots.length).toBeGreaterThan(1);for(const s of snapshots){expect(s.entities.some(p=>p.id===m.id)).toBe(false);expect(JSON.stringify(s)).not.toContain('"choices"');expect(JSON.stringify(s)).not.toContain('"depart"');}});
  it('validates exit selection against authenticated ownership, listed exits and plugs',()=>{const f=fixture(),m=enter(f);const original=m.transit!.exit,choice=m.transit!.choices.find(id=>id!==original)!;expect(choice).toBeDefined();f.send(f.b,{type:'transitExit',exit:choice,playerId:m.id});expect(m.transit!.exit).toBe(original);f.send(f.a,{type:'transitExit',exit:'forged'});expect(m.transit!.exit).toBe(original);f.room.world!.plugs[choice]=100;f.send(f.a,{type:'transitExit',exit:choice});expect(m.transit!.exit).toBe(original);delete f.room.world!.plugs[choice];f.send(f.a,{type:'transitExit',exit:choice});expect(m.transit!.exit).toBe(choice);const arrive=m.transit!.arrive;while(f.room.world!.time<arrive+DT)f.tick(0);expect(m.transit).toBeUndefined();expect(m.state).toBe('free');const h=MAP3D.holes.find(h=>h.id===choice)!;expect(m.x).toBeCloseTo(h.x);expect(m.y).toBeCloseTo(h.y);});
  it('reconnects during transit with stable identity, cargo, destination and authoritative arrival',()=>{const f=fixture(),m=enter(f);m.carry='tomato';const transit={...m.transit!};f.rooms.disconnect(f.a.id);f.advance(250);const replacement=peer('new-mouse');f.send(replacement,{type:'join',code:f.joined.code,name:'Mouse',token:f.joined.token});expect(replacement.messages.find(v=>v.type==='joined')).toMatchObject({playerId:m.id});const self=latest(replacement).entities.find(p=>p.id===m.id)!;expect(self).toMatchObject({mode:'3d',carry:'tomato',state:'transit',transit});expect(m.bot).toBe(false);});
  it('preserves a transit through room persistence without publishing private fields to a reconnecting chef',()=>{const f=fixture(),m=enter(f),saved=JSON.parse(JSON.stringify(f.rooms.exportState())),bJoin=f.b.messages.find(v=>v.type==='joined');if(bJoin?.type!=='joined')throw Error('Missing chef join');const restored=new Rooms();restored.now=()=>101000;restored.restoreState(saved);const chef=peer('restored-chef');restored.receive(chef,JSON.stringify({type:'join',code:f.room.code,name:'Chef',token:bJoin.token}));const w=restored.rooms.get(f.room.code)!.world!;expect(w.mode).toBe('3d');expect(w.players.find(p=>p.id===m.id)?.transit?.arrive).toBe(m.transit!.arrive);expect(latest(chef).entities.some(p=>p.id===m.id)).toBe(false);});
  it('keeps room mode fixed across host settings and rematch',()=>{const f=fixture();f.room.world!.heist=100;f.tick();f.send(f.a,{type:'rematch'});f.send(f.a,{type:'host',options:{mode:'2d'}});expect(f.room.phase).toBe('lobby');expect(f.room.options.mode).toBe('3d');});
});
