import {describe,it,expect} from 'vitest';
import {Rooms,type Peer} from '../server/rooms';
import {snapshotFor} from '../server/interest';
import {createWorld,stepWorld} from '../shared/sim';
import {BUTTON} from '../shared/constants';
import {WireDecoder,WireEncoder} from '../shared/wire';
import type {ServerMessage,Snapshot,InputFrame,LobbyPlayer} from '../shared/protocol';
const roster:LobbyPlayer[]=[{id:'m',name:'Mouse',team:'mouse',classId:'scout',ready:true,bot:false,connected:true},{id:'c',name:'Chef',team:'chef',classId:'head',ready:true,bot:false,connected:true}];
function peer(id:string){const messages:ServerMessage[]=[];const decoder=new WireDecoder();return {id,messages,send:(s:string)=>{const m=decoder.decode(s);if(m)messages.push(m);},close:()=>{}};}
function fixture(start=true){const rooms=new Rooms();let time=100000;rooms.now=()=>time;const a=peer('a'),b=peer('b');const send=(p:Peer,m:unknown)=>rooms.receive(p,JSON.stringify(m));send(a,{type:'create',name:'Mouse',team:'mouse'});const joined=a.messages.find(m=>m.type==='joined')!;if(joined.type!=='joined')throw Error('not joined');send(b,{type:'join',name:'Chef',code:joined.code});send(b,{type:'setTeam',team:'chef'});send(a,{type:'host',options:{bots:false}});const room=rooms.rooms.get(joined.code)!;
  const begin=()=>{send(a,{type:'ready',value:true});send(b,{type:'ready',value:true});send(a,{type:'start'});send(a,{type:'skip'});send(b,{type:'skip'});rooms.tick();};if(start)begin();return {rooms,a,b,room,send,joined,begin,advance:(ms:number)=>time+=ms};}
const frame=(seq:number,extra:Partial<InputFrame>={}):InputFrame=>({seq,tick:1,mx:0,my:0,buttons:0,ax:30,ay:30,...extra});
const latestSnap=(p:ReturnType<typeof peer>)=>p.messages.filter((m):m is Snapshot=>m.type==='snap').at(-1)!;

describe('room authority and lifecycle',()=>{
  it('shares a captive ping only with teammates and limits repeated pings',()=>{const w=createWorld(roster,{duration:480,bots:false,difficulty:'normal'},7);const m=w.players[0],c=w.players[1];m.state='caged';m.stateUntil=40;stepWorld(w,new Map([[m.id,frame(1,{buttons:BUTTON.PING})]]));expect(snapshotFor(w,m).events.filter(e=>e.kind==='ping')).toHaveLength(1);expect(snapshotFor(w,m).events.find(e=>e.kind==='ping')?.text).toContain('Help here');expect(snapshotFor(w,c).events.filter(e=>e.kind==='ping')).toHaveLength(0);stepWorld(w,new Map());stepWorld(w,new Map([[m.id,frame(2,{buttons:BUTTON.PING})]]));expect(w.events.filter(e=>e.kind==='ping')).toHaveLength(1);});
  it('creates, joins, starts and synchronizes both clients on the same tick and timer',()=>{const f=fixture();f.rooms.tick();const a=latestSnap(f.a),b=latestSnap(f.b);expect(f.room.members).toHaveLength(2);expect(a.tick).toBe(b.tick);expect(a.time).toBe(b.time);expect(a.heist).toBe(b.heist);expect(a.rating).toBe(b.rating);expect(f.room.phase).toBe('match');});
  it('requires readiness and host authority',()=>{const f=fixture(false);f.send(f.b,{type:'start'});expect(f.room.phase).toBe('lobby');f.send(f.a,{type:'start'});expect(f.room.phase).toBe('lobby');expect(f.a.messages.at(-1)?.type).toBe('error');f.send(f.b,{type:'host',options:{duration:600,bots:true}});expect(f.room.options).toMatchObject({duration:480,bots:false});});
  it('rejects malformed, oversized, illegal and duplicate input without spoofing another player',()=>{const f=fixture();const own=f.joined.playerId,other=f.room.members[1].player.id;for(const raw of ['{','null','[]','1','x'.repeat(2049)])expect(()=>f.rooms.receive(f.a,raw)).not.toThrow();for(const value of [null,{},frame(1,{mx:2}),frame(-1),frame(1,{buttons:9999}),frame(1,{mx:NaN})])f.send(f.a,{type:'input',frame:value});expect(f.room.inputs.has(own)).toBe(false);f.send(f.a,{type:'input',playerId:other,frame:frame(2,{mx:1})});expect(f.room.inputs.has(other)).toBe(false);expect(f.room.inputs.get(own)?.seq).toBe(2);f.send(f.a,{type:'input',frame:frame(2,{mx:-1})});expect(f.room.inputs.get(own)?.mx).toBe(1);});
  it('limits joined peers to forty messages in a second',()=>{const f=fixture();f.advance(1001);for(let i=1;i<=80;i++)f.send(f.a,{type:'input',frame:frame(i)});expect(f.room.inputs.get(f.joined.playerId)?.seq).toBe(40);});
  it('restores identity, team, class and carried item after a match disconnect',()=>{const f=fixture();const p=f.room.world!.players.find(p=>p.id===f.joined.playerId)!;p.carry='cheese';p.classId='rescuer';f.rooms.disconnect(f.a.id);expect(p.connected).toBe(false);expect(f.room.hostId).toBe(f.room.members[1].player.id);f.advance(59000);const replacement=peer('replacement');f.send(replacement,{type:'join',code:f.room.code,name:'Replacement',token:f.joined.token});expect(replacement.messages.find(m=>m.type==='joined')).toMatchObject({playerId:p.id});expect(p).toMatchObject({team:'mouse',classId:'rescuer',carry:'cheese',connected:true,bot:false});});
  it('preserves lobby identity and class on reconnect within sixty seconds',()=>{const f=fixture(false);f.send(f.a,{type:'setClass',class:'rescuer',classId:'rescuer'});f.rooms.disconnect(f.a.id);f.advance(10000);const replacement=peer('replacement');f.send(replacement,{type:'join',code:f.room.code,name:'Mouse',token:f.joined.token});expect(replacement.messages.find(m=>m.type==='joined')).toMatchObject({playerId:f.joined.playerId});expect(f.room.members.find(m=>m.player.id===f.joined.playerId)?.player.classId).toBe('rescuer');});
  it('turns a disconnected player over to a bot after five seconds',()=>{const f=fixture();const p=f.room.world!.players[0];f.rooms.disconnect(f.a.id);f.advance(4999);f.rooms.tick();expect(p.bot).toBe(false);f.advance(2);f.rooms.tick();expect(p.bot).toBe(true);});
  it('broadcasts one result and resets into a playable rematch',()=>{const f=fixture();f.room.world!.heist=100;f.rooms.tick();expect(f.room.phase).toBe('results');expect(f.a.messages.filter(m=>m.type==='result')).toHaveLength(1);expect(f.b.messages.filter(m=>m.type==='result')).toHaveLength(1);f.rooms.tick();expect(f.a.messages.filter(m=>m.type==='result')).toHaveLength(1);f.send(f.a,{type:'rematch'});expect(f.room.phase).toBe('lobby');expect(f.room.world).toBeUndefined();expect(f.room.members.every(m=>!m.player.ready)).toBe(true);});
  it('resets input sequence acceptance for a new match',()=>{const f=fixture();f.send(f.a,{type:'input',frame:frame(100)});f.room.world!.heist=100;f.rooms.tick();f.send(f.a,{type:'rematch'});f.begin();f.send(f.a,{type:'input',frame:frame(1,{mx:1})});expect(f.room.inputs.get(f.joined.playerId)?.seq).toBe(1);});
  it('restored persistent room gives host authority to the first reconnecting human',()=>{const f=fixture();const bJoin=f.b.messages.find(m=>m.type==='joined')!;if(bJoin.type!=='joined')throw Error('join missing');const saved=JSON.parse(JSON.stringify(f.rooms.exportState()));const restored=new Rooms();restored.now=()=>110000;restored.restoreState(saved);const p=peer('restored-b');restored.receive(p,JSON.stringify({type:'join',code:f.room.code,name:'Chef',token:bJoin.token}));expect(restored.rooms.get(f.room.code)?.hostId).toBe(bJoin.playerId);expect(restored.rooms.get(f.room.code)?.world?.players.find(v=>v.id===f.joined.playerId)?.connected).toBe(false);});
  it('does not revive an expired reconnect token after persistence restore',()=>{const f=fixture();f.rooms.disconnect(f.a.id);const saved=JSON.parse(JSON.stringify(f.rooms.exportState()));const restored=new Rooms();restored.now=()=>170001;restored.restoreState(saved);const replacement=peer('late');restored.receive(replacement,JSON.stringify({type:'join',code:f.room.code,token:f.joined.token,name:'Late Mouse'}));const joined=replacement.messages.find(m=>m.type==='joined');expect(joined?.type==='joined'&&joined.playerId).not.toBe(f.joined.playerId);});
  it('replacing an active connection discards its private delta baseline',()=>{const f=fixture();f.rooms.tick();expect(f.rooms.encoders.has(f.a.id)).toBe(true);const replacement=peer('replacement');f.send(replacement,{type:'join',code:f.room.code,token:f.joined.token,name:'Mouse'});expect(f.rooms.peers.has(f.a.id)).toBe(false);expect(f.rooms.encoders.has(f.a.id)).toBe(false);});
  it('drops stale movement after 250ms and ignores unsolicited probe echoes',()=>{const f=fixture();f.send(f.a,{type:'input',frame:frame(1,{mx:1})});f.advance(251);f.rooms.tick();expect(f.room.inputs.has(f.joined.playerId)).toBe(false);const link=f.rooms.peers.get(f.a.id)!;const before=link.samples.slice();f.send(f.a,{type:'probe',nonce:'invented'});expect(link.samples).toEqual(before);const nonce=link.probe?.nonce;expect(nonce).toBeDefined();f.advance(120);f.send(f.a,{type:'probe',nonce});expect(link.samples.at(-1)).toBe(371);});
  it('uses the PartyKit actor code and rejects duplicate room creation',()=>{const rooms=new Rooms('ABCD'),a=peer('fixed-a'),b=peer('fixed-b');rooms.receive(a,JSON.stringify({type:'create',name:'A',team:'mouse'}));expect(a.messages.find(m=>m.type==='joined')).toMatchObject({code:'ABCD'});rooms.receive(b,JSON.stringify({type:'create',name:'B'}));expect(b.messages.at(-1)?.type).toBe('error');expect(rooms.rooms.size).toBe(1);});
  it('ignores malformed probe messages before and after joining',()=>{const rooms=new Rooms(),p=peer('probe-attacker');expect(()=>rooms.receive(p,JSON.stringify({type:'probe'}))).not.toThrow();rooms.receive(p,JSON.stringify({type:'create',name:'A'}));expect(()=>rooms.receive(p,JSON.stringify({type:'probe'}))).not.toThrow();});
  it('cleans encoder state when an unjoined connection closes',()=>{const rooms=new Rooms(),p=peer('prejoin');rooms.receive(p,JSON.stringify({type:'time',t0:1}));rooms.disconnect(p.id);expect(rooms.encoders.has(p.id)).toBe(false);});
});

describe('hidden-information snapshots use actual simulation visibility',()=>{
  function world(){const w=createWorld(roster,{duration:480,bots:false,difficulty:'normal'});Object.assign(w.players[0],{x:35,y:24,layer:'floor',vx:0,vy:0});Object.assign(w.players[1],{x:37,y:24,angle:Math.PI});return w;}
  it.each(['tunnel','hide','camouflage'])('never sends %s mouse or actor event to chefs',kind=>{const w=world(),[mouse,chef]=w.players;if(kind==='tunnel')mouse.layer='tunnel';if(kind==='hide')mouse.hidden='hide-table-1';if(kind==='camouflage'){mouse.buff='camouflage';mouse.buffUntil=10;}w.events.push({id:1,kind:'footstep',text:'Hidden action',x:mouse.x,y:mouse.y,time:0,playerId:mouse.id});const s=JSON.parse(JSON.stringify(snapshotFor(w,chef))) as Snapshot;expect(s.entities.some(p=>p.id===mouse.id)).toBe(false);expect(s.events).toHaveLength(0);});
  it('reveals a nearby visible enemy but strips every private combat field both ways',()=>{const w=world();for(const viewer of w.players){const other=w.players.find(p=>p.id!==viewer.id)!;other.cooldowns={secret:99};other.stamina=43;other.composure=72;const entity=snapshotFor(w,viewer).entities.find(p=>p.id===other.id);expect(entity).toBeDefined();for(const key of ['cooldowns','stamina','composure','buff','buffUntil','buffUses','action','stats','hidden'])expect(entity).not.toHaveProperty(key);}});
  it('allows an explicit radar reveal without leaking private stats',()=>{const w=world(),[mouse,chef]=w.players;mouse.layer='tunnel';mouse.revealUntil=3;expect(snapshotFor(w,chef).entities.find(p=>p.id===mouse.id)).toBeDefined();});
  it('limits enemy traps to two tiles and keeps tamper detail off chef orders',()=>{const w=world(),[mouse,chef]=w.players;w.traps=[{id:'near',x:mouse.x+2,y:mouse.y,team:'chef',owner:chef.id,armedAt:0,expires:100},{id:'far',x:mouse.x+2.01,y:mouse.y,team:'chef',owner:chef.id,armedAt:0,expires:100}];w.orders=[{id:'o',tableId:'g',stage:'ready',elapsed:0,age:30,readyAt:30,cold:false,vip:false,tamper:'chili'}];expect(snapshotFor(w,mouse).traps.map(t=>t.id)).toEqual(['near']);expect(snapshotFor(w,chef).traps).toHaveLength(2);expect(snapshotFor(w,chef).orders[0]).not.toHaveProperty('tamper');expect(w.orders[0].tamper).toBe('chili');});
  it('does not reveal remote enemy position through an ability event',()=>{const w=world(),[mouse,chef]=w.players;Object.assign(mouse,{x:65,y:10});chef.classId='head';stepWorld(w,new Map([[chef.id,frame(1,{buttons:BUTTON.ABILITY,ax:38,ay:24})]]));expect(w.events.some(e=>e.kind==='slam')).toBe(true);const s=snapshotFor(w,mouse);expect(s.entities.some(p=>p.id===chef.id)).toBe(false);expect(s.events.filter(e=>e.kind==='slam')).toHaveLength(0);});
});

describe('wire delta privacy and baseline',()=>{
  it('removes an enemy from reconstructed state immediately when entering a hole',()=>{const w=createWorld(roster,{duration:480,bots:false,difficulty:'normal'});const [m,c]=w.players;Object.assign(m,{x:35,y:24,layer:'floor'});Object.assign(c,{x:37,y:24,angle:Math.PI});const enc=new WireEncoder(),dec=new WireDecoder();const first=dec.decode(enc.encode(snapshotFor(w,c))) as Snapshot;expect(first.entities.some(p=>p.id===m.id)).toBe(true);m.layer='tunnel';const next=dec.decode(enc.encode(snapshotFor(w,c))) as Snapshot;expect(next.entities.some(p=>p.id===m.id)).toBe(false);expect(first.entities.some(p=>p.id===m.id)).toBe(true);});
  it('removes obsolete private optional fields instead of retaining a stale carry or buff',()=>{const w=createWorld(roster,{duration:480,bots:false,difficulty:'normal'});const m=w.players[0],enc=new WireEncoder(),dec=new WireDecoder();m.carry='cheese';m.buff='dash';dec.decode(enc.encode(snapshotFor(w,m)));m.carry=undefined;m.buff=undefined;const next=dec.decode(enc.encode(snapshotFor(w,m))) as Snapshot;expect(next.entities.find(p=>p.id===m.id)).not.toHaveProperty('carry');expect(next.entities.find(p=>p.id===m.id)).not.toHaveProperty('buff');});
  it('starts with a complete snapshot after connection baseline reset',()=>{const w=createWorld(roster,{duration:480,bots:false,difficulty:'normal'}),enc=new WireEncoder();enc.encode(snapshotFor(w,w.players[0]));enc.reset();const fresh=enc.encode(snapshotFor(w,w.players[1]));expect(JSON.parse(fresh).type).toBe('snap');expect(new WireDecoder().decode(fresh)).toEqual(JSON.parse(fresh));});
});
