import fs from 'node:fs';
import path from 'node:path';

// Run after scripts/presentation-audit.mjs and scripts/motion-record.mjs.
const output='client/public/presentation';
fs.mkdirSync(output,{recursive:true});
const screens=[
 ['mouse-hud-desktop','Desktop gameplay HUD'],['mouse-hud-844','Landscape gameplay HUD'],
 ['carrying','Food and paws in actual gameplay'],['kitchen-floor-hud','Mouse scale and kitchen lighting'],
 ['lobby-mice','Lobby and mouse selection'],['role-chefs','Chef selection'],
 ['settings-keys','Settings and keyboard controls'],['results-phone','Landscape results'],
 ['chef-hud-phone','Chef gameplay HUD'],['home-desktop','Home screen']
];
const copy=(source,target)=>fs.copyFileSync(source,path.join(output,target));
for(const [name]of screens)for(const stage of ['before','after'])copy(`evidence/presentation/${stage}/${name}.png`,`${stage}-${name}.png`);
for(const name of ['touch-650-right','chef-capture','status-stress'])copy(`evidence/presentation/after/${name}.png`,`${name}.png`);
for(const stage of ['before','after'])copy(`evidence/presentation/${stage}/motion.webm`,`${stage}-motion.webm`);
copy('evidence/presentation/after-front/motion.webm','after-front.webm');
copy('evidence/presentation/after/gameplay-and-ui.webm','tutorials-and-ui.webm');
for(const name of ['jump','climb','carry-eat','capture-rescue','heavy-food'])copy(`evidence/presentation/after-front/${name}-sequence.png`,`${name}-sequence.png`);
const perf=JSON.parse(fs.readFileSync('work/performance3d-hardware.json','utf8'));
const before=JSON.parse(fs.readFileSync('evidence/presentation/before/performance.json','utf8'));
const audit=JSON.parse(fs.readFileSync('evidence/presentation/after/audit.json','utf8'));
const motion=JSON.parse(fs.readFileSync('evidence/presentation/after/motion.json','utf8'));
const summary={date:'2026-10-09',baselineDate:'2026-10-08',iterations:6,screenAudit:audit,performance:perf,baselinePerformance:before,
 contrast:JSON.parse(fs.readFileSync('work/presentation-contrast.json','utf8')),checks:fs.existsSync('work/presentation-checks.json')?JSON.parse(fs.readFileSync('work/presentation-checks.json','utf8')):undefined,
 animation:{frames:motion.samples.length,errors:motion.errors,maxFlipRadians:Math.max(...motion.samples.map(s=>s.flip)),
 review:'Sequential frames extracted from recorded video; jump samples 55 ms apart, sprint/landing 120 ms. Clip players expose normal and slow playback. Capture, cage and rescue lab segments are labeled state fixtures; tutorial capture uses working controls.'},
 limitations:['Touch layouts are desktop Chrome emulation, not physical phone performance.','Eight simultaneously active human devices have not been tested.','Silent browser recordings do not verify audible sound quality.','The results screen audit uses a deterministic result-message fixture, not a finished match.']};
fs.writeFileSync(path.join(output,'summary.json'),JSON.stringify(summary,null,2));
const compare=screens.map(([name,title])=>`<section class="comparison"><h2>${title}</h2><div class="pair">${['before','after'].map(stage=>`<figure><figcaption>${stage==='before'?'Before':'After six passes'}</figcaption><a href="${stage}-${name}.png"><img loading="lazy" src="${stage}-${name}.png" alt="${stage}: ${title}"></a></figure>`).join('')}</div></section>`).join('');
const table=perf.profiles.map((p,i)=>`<tr><td>${p.quality}</td><td>${before.profiles[i].fps.toFixed(1)}</td><td>${p.fps.toFixed(1)}</td><td>${(before.profiles[i].heap/1048576).toFixed(0)} / ${(p.heap/1048576).toFixed(0)} MiB</td></tr>`).join('');
const html=`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Sous Mice - Presentation review</title><style>
 :root{color-scheme:dark;font:16px/1.6 system-ui,sans-serif;background:#271d32;color:#f5e7d3}*{box-sizing:border-box}body{margin:0}main{max-width:1440px;margin:auto;padding:30px 24px 80px}header{display:flex;align-items:center;justify-content:space-between;gap:20px}h1{font-size:clamp(28px,4vw,48px);line-height:1.15;margin:24px 0 12px}h2{font-size:23px;margin:0 0 16px}h3{font-size:18px;margin:10px 0}p{max-width:880px;color:#d2c4c6}.tag{font-size:12px;letter-spacing:2px;color:#edbd7d}a{color:#b3deca}button,.play{background:#f2bc71;color:#352437;border:1px solid #ffdb9c;border-radius:10px;padding:10px 16px;font:700 14px system-ui;text-decoration:none;cursor:pointer;min-height:44px}button:hover,.play:hover{background:#ffd79c}button:focus-visible,a:focus-visible{outline:3px solid #8ecabc;outline-offset:4px}.panel,.comparison{margin-top:32px;padding:22px;background:#352a3c;border:1px solid #715a64;border-radius:18px}.pair{display:grid;grid-template-columns:1fr 1fr;gap:18px}figure{margin:0;min-width:0}figcaption{font-size:13px;color:#e6c9a8;margin-bottom:8px}img,video{display:block;width:100%;border-radius:10px;background:#211a28}video{aspect-ratio:16/9}.tools{display:flex;flex-wrap:wrap;gap:8px;margin:14px 0}.tools button{background:#483744;color:#f5e7d3;border-color:#927367}.tools button[aria-pressed=true]{background:#f2bc71;color:#352437}.small{font-size:13px}.single{max-width:960px}table{border-collapse:collapse;width:100%;max-width:800px}th,td{padding:10px;text-align:left;border-bottom:1px solid #715a64}th{color:#edbd7d}ol,ul{padding-left:24px}li{margin:7px 0}details summary{cursor:pointer;color:#b3deca;min-height:44px;display:flex;align-items:center}@media(max-width:720px){main{padding:20px 12px 50px}.pair{grid-template-columns:1fr}.panel,.comparison{padding:14px}header{align-items:flex-start}table{font-size:12px}th,td{padding:8px 5px}}@media(prefers-reduced-motion:reduce){*{scroll-behavior:auto}}
 </style></head><body><main><header><span class="tag">SOUS MICE / OCTOBER 9, 2026</span><a class="play" href="/?r=3d">Play the updated game</a></header><h1>A clearer heist. More expressive little paws.</h1><p>Six presentation passes: compact objectives and controls; blended character motion and camera follow; food, paws and kitchen-hand alignment; capture, sprint and memory refinements. Screens below come from actual menus and gameplay.</p>
 <section class="panel"><h2>Animation comparison</h2><p class="small">Recorded movement uses the real controller. Capture, cage and rescue in these lab clips are state fixtures. The full tutorial recording below performs both tutorials through working controls. Recordings are silent.</p><div class="pair"><figure><figcaption>Before / 31-second sequence</figcaption><video data-lab="31" controls playsinline preload="metadata" src="before-motion.webm"></video></figure><figure><figcaption>After / 35-second sequence, with oversized food</figcaption><video data-lab="35" controls playsinline preload="metadata" src="after-motion.webm"></video></figure></div><div class="tools" aria-label="Playback speed"><button data-rate="1" aria-pressed="true">Normal speed</button><button data-rate="0.5" aria-pressed="false">Half speed</button><button data-rate="0.25" aria-pressed="false">Quarter speed</button></div><div class="tools" aria-label="Animation chapters">${[[0,'Idle / walk'],[4,'Sprint'],[8,'Jump / landing'],[10,'Climb'],[13,'Carry / eat'],[19,'Capture / rescue'],[27,'Run / jump / turn']].map(([t,label])=>`<button data-seek="${t}">${label}</button>`).join('')}</div><p class="small">Chapter alignment is approximate; the recorded phase label is the reference. Native video controls allow individual scrubbing.</p><details><summary>Front angle and frame sequences</summary><video class="single" controls playsinline preload="none" src="after-front.webm"></video>${['jump','climb','carry-eat','capture-rescue','heavy-food'].map(n=>`<figure style="margin-top:18px"><figcaption>${n.replaceAll('-',' ')} / frames sampled from recorded video</figcaption><a href="${n}-sequence.png"><img loading="lazy" src="${n}-sequence.png" alt="Recorded ${n.replaceAll('-',' ')} frame sequence"></a></figure>`).join('')}</details></section>
 <section class="panel"><h2>Actual gameplay and screen tour</h2><video class="single" controls playsinline preload="none" src="tutorials-and-ui.webm"></video><p class="small">Home, lobby, role selection, settings, the complete mouse and chef tutorials, and results. The results panel is exercised using a deterministic message fixture.</p></section>
 ${compare}<section class="panel"><h2>Additional checks</h2><div class="pair"><figure><figcaption>650 x 360 touch layout / large controls / reduced motion</figcaption><a href="touch-650-right.png"><img loading="lazy" src="touch-650-right.png" alt="Compact touch controls and objective without overlap"></a></figure><figure><figcaption>Capture through the real chef tutorial</figcaption><a href="chef-capture.png"><img loading="lazy" src="chef-capture.png" alt="Chef carrying a captured mouse in the tutorial"></a></figure></div></section>
 <section class="panel"><h2>Short-screen status stress</h2><img class="single" loading="lazy" src="status-stress.png" alt="650 by 360 layout with carrying and buff status fixture"><p class="small">The real HUD is frozen for this labeled layout fixture; simultaneous carrying and buff status remain clear of the objective.</p></section><section class="panel"><h2>What the iterations verified</h2><ol><li>Separated objective, status, context and controls; folded optional instructions and minimap. Fixed return-button pointer lock and stale binding labels.</li><li>Blended shortest-path turns, travel-based gait and action changes. Added controlled flips, landing compression, expressive ears, tails and blinking. Smoothed camera follow with collision checks.</li><li>Reviewed front and follow footage: lowered food into the paws, leveled feet, attached utensils and trays to hands, and added camera clearance around chair rails and cloth.</li><li>Made captured mice visible on the chef's hand, moved oversized food beside the mouse, reduced unreadable sprint cadence, kept lobby start actions visible, and removed unnecessary world geometry detail.</li><li>Front-angle heavy-food review exposed a blocked mouse. Widened and raised the follow camera while dragging, then restored distant human sphere budgets while retaining close mouse detail.</li><li>A short-screen fixture exposed a 7-pixel overlap with carrying and buff status together. Tightened the objective card and added a regression check for that combined status.</li></ol><table><thead><tr><th>Quality</th><th>Before FPS</th><th>After FPS</th><th>Before / after sampled JS heap</th></tr></thead><tbody>${table}</tbody></table><p class="small">${perf.environment} Ten-second stationary samples per quality, two players and six moving kitchen cooks. This measures JS heap, not total device memory. GPU: ${perf.gpu}.</p><p class="small">Remaining verification limits: physical phone performance, eight active human devices, and audible sound quality. Results layout uses a fixture. Visual review used temporal frame sequences extracted from the clips; the players above provide normal and slow playback.</p><a href="summary.json">Detailed audit and measurements</a></section></main><script>
 const videos=[...document.querySelectorAll('video')];document.querySelectorAll('[data-rate]').forEach(b=>b.onclick=()=>{videos.forEach(v=>v.playbackRate=Number(b.dataset.rate));document.querySelectorAll('[data-rate]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));});document.querySelectorAll('[data-seek]').forEach(b=>b.onclick=()=>{document.querySelectorAll('video[data-lab]').forEach(v=>{if(!Number.isFinite(v.duration))return;v.currentTime=Math.max(0,v.duration-Number(v.dataset.lab)-1.1+Number(b.dataset.seek));v.play().catch(()=>{});});});
 </script></body></html>`;
fs.writeFileSync(path.join(output,'index.html'),html);
console.log(JSON.stringify({screens:screens.length,files:fs.readdirSync(output).length,bytes:fs.readdirSync(output).reduce((n,f)=>n+fs.statSync(path.join(output,f)).size,0)}));
