import {chromium,expect} from '@playwright/test';import fs from 'node:fs';
const stage=process.env.PASS||'after',base=process.env.GAME_URL||'http://127.0.0.1:5173',out=`evidence/presentation/${stage}`;fs.mkdirSync(out,{recursive:true});
const browser=await chromium.launch({channel:'chrome',headless:true}),errors=[],shots=[];
const ctx=await browser.newContext({viewport:{width:1440,height:900},recordVideo:{dir:`work/presentation-video-${stage}`,size:{width:1440,height:900}}});
await ctx.addInitScript(()=>{localStorage.setItem('sous-settings-3d',JSON.stringify({quality:'high'}));});const p=await ctx.newPage();p.on('pageerror',e=>errors.push(e.message));let socket,playerId;
p.on('websocket',ws=>ws.on('framereceived',f=>{try{const m=JSON.parse(String(f.payload));if(m.type==='joined')playerId=m.playerId;}catch{}}));
await p.routeWebSocket(u=>u.pathname==='/ws'||u.pathname.startsWith('/parties/'),w=>{socket=w;w.connectToServer();});
const shot=async name=>{await p.waitForTimeout(800);await p.screenshot({path:`${out}/${name}.png`,fullPage:!name.includes('hud')});shots.push(name);};
try{
 await p.goto(base+'?r=3d');await shot('home-desktop');await p.locator('#create').click();await shot('create-dialog');await p.locator('#nickname').fill('Juniper');await p.getByRole('button',{name:'Create room',exact:false}).click();await p.locator('#lobby-code').waitFor();await shot('lobby-mice');await p.locator('#team-chef').click();await p.waitForTimeout(350);await shot('role-chefs');
 for(const [width,height]of [[1024,768],[844,390],[390,844]]){await p.setViewportSize({width,height});await shot(`lobby-${width}`);}await p.setViewportSize({width:1440,height:900});
 await p.locator('#training').click();await shot('role-training');await p.locator('#learn-mouse').click();await p.waitForFunction(()=>window.__sous3d?.metrics()?.frames>5);await shot('mouse-hud-desktop');
 for(const [width,height]of [[1024,768],[844,390],[932,430]]){await p.setViewportSize({width,height});await shot(`mouse-hud-${width}`);}await p.setViewportSize({width:1440,height:900});
 await p.locator('#pause').click();await shot('pause');await p.locator('#open-settings').click();await shot('settings');await p.getByText('3D keyboard controls',{exact:true}).click();await p.locator('[data-remap3d=use]').scrollIntoViewIfNeeded();await shot('settings-keys');await p.locator('#modal-close').click();
 const step=()=>p.evaluate(()=>window.__sous3d.state().trainingStep);const key=async(k,next)=>{await p.keyboard.down(k);try{await expect.poll(step,{timeout:20000}).toBe(next);}finally{await p.keyboard.up(k);}};
 await p.locator('canvas[data-engine]').click({position:{x:720,y:450}});await p.mouse.move(950,420);await p.keyboard.down('ControlLeft');await key('KeyW',1);await p.keyboard.up('ControlLeft');await shot('kitchen-floor-hud');await key('Space',2);await p.keyboard.down('KeyE');await key('KeyW',3);await p.keyboard.up('KeyE');await key('KeyC',4);await key('KeyE',5);await shot('carrying');await key('KeyF',6);await shot('eating-end');for(let s=7;s<=11;s++)await key('KeyE',s);await shot('training-complete');if(stage==='before'&&await p.evaluate(()=>!!document.pointerLockElement)){await p.keyboard.press('Escape');if(await p.locator('#modal-close').isVisible())await p.locator('#modal-close').click();}await p.locator('#finish-training').click();
 await p.locator('#training').click();await p.locator('#learn-chef').click();await p.waitForFunction(()=>window.__sous3d?.metrics()?.frames>5);await shot('chef-hud-desktop');await p.setViewportSize({width:844,height:390});await shot('chef-hud-phone');await p.setViewportSize({width:1440,height:900});await key('KeyE',1);await key('KeyI',2);await p.keyboard.press('KeyQ');await expect.poll(step).toBe(3);await key('KeyE',4);await shot('chef-capture');await key('KeyT',5);await key('KeyE',6);await key('KeyB',7);await key('KeyN',8);await shot('chef-training-complete');await p.locator('#finish-training').click();
 // A deterministic result message exercises the real results renderer; no match is claimed.
 const ids=await p.locator('.player-row b').allTextContents();socket.send(JSON.stringify({type:'result',result:{winner:'mouse',reason:'The Colony brought home a feast.',stats:{[playerId]:{deliveries:4,captures:0,rescues:2,dishes:0,tampers:1,scares:2}}}}));await p.locator('.results-screen').waitFor();await shot('results-desktop');await p.setViewportSize({width:844,height:390});await shot('results-phone');
 const bounds=await p.evaluate(()=>({viewport:[innerWidth,innerHeight],document:[document.documentElement.scrollWidth,document.documentElement.scrollHeight]}));await ctx.close();await p.video().saveAs(`${out}/gameplay-and-ui.webm`);fs.writeFileSync(`${out}/audit.json`,JSON.stringify({stage,base,shots,errors,bounds,results:'Real renderer with deterministic result-message fixture, not a completed match.',video:'gameplay-and-ui.webm'},null,2));console.log(JSON.stringify({stage,shots:shots.length,errors}));
}finally{await browser.close();}

