import {settings} from '../settings';
import type {EntityView,GameEvent} from '../../shared/protocol';
/** Original synthesized spatial foley. No speech recordings or external audio. */
export class SpatialKitchenAudio {
 private ctx?:AudioContext;private master?:GainNode;private seen=new Set<number>();private foot=0;private transit=false;private stopped=false;
 constructor(){window.addEventListener('pointerdown',this.unlock,{once:true});window.addEventListener('keydown',this.unlock,{once:true});}
 private unlock=()=>{if(this.stopped)return;this.ctx??=new AudioContext();this.master??=this.ctx.createGain();this.master.connect(this.ctx.destination);void this.ctx.resume();};
 private tone(x:number,y:number,z:number,freq:number,duration:number,gain:number,occluded=false){const c=this.ctx;if(!c||!this.master||settings.muted)return;const o=c.createOscillator(),g=c.createGain(),p=c.createPanner(),filter=c.createBiquadFilter();o.type=freq<150?'sine':'triangle';o.frequency.setValueAtTime(freq,c.currentTime);o.frequency.exponentialRampToValueAtTime(freq*.55,c.currentTime+duration);g.gain.setValueAtTime(0,c.currentTime);g.gain.linearRampToValueAtTime(gain*settings.sfx,c.currentTime+.006);g.gain.exponentialRampToValueAtTime(.0001,c.currentTime+duration);p.panningModel='HRTF';p.distanceModel='inverse';p.refDistance=freq<150?2:.6;p.maxDistance=16;p.rolloffFactor=1.1;p.positionX.value=x;p.positionY.value=z;p.positionZ.value=y;filter.type='lowpass';filter.frequency.value=occluded?350:freq<150?650:6000;o.connect(g).connect(filter).connect(p).connect(this.master);o.start();o.stop(c.currentTime+duration+.02);}
 update(self:EntityView,yaw:number,pitch:number,time:number,events:GameEvent[],speed:number){const c=this.ctx;if(!c||!this.master)return;this.master.gain.value=settings.muted?0:.65;const l=c.listener;if(l.positionX){l.positionX.value=self.x;l.positionY.value=(self.z||0)+(self.team==='mouse'?.07:1.65);l.positionZ.value=self.y;l.forwardX.value=Math.cos(yaw)*Math.cos(pitch);l.forwardY.value=Math.sin(pitch);l.forwardZ.value=Math.sin(yaw)*Math.cos(pitch);l.upX.value=0;l.upY.value=1;l.upZ.value=0;}if(speed>.1&&time-this.foot>(self.team==='mouse'?.12:.45)&&self.state==='free'){this.foot=time;this.tone(self.x,self.y,self.z||0,self.team==='mouse'?740:64,self.team==='mouse'?.045:.18,self.team==='mouse'?.025:.1);}for(const e of events){if(this.seen.has(e.id))continue;this.seen.add(e.id);if(time-e.time>1)continue;const near=Math.hypot(e.x-self.x,e.y-self.y);if(near>(e.radius||12))continue;const step=/foot|tremor/.test(e.kind);this.tone(e.x,e.y,e.z||0,step?48:/capture|cage|colander/.test(e.kind)?160:/eat|deliver|rescue/.test(e.kind)?960:420,step?.3:.16,step?.3:.08);}if(this.seen.size>400)this.seen=new Set(events.map(e=>e.id));if(!!self.transit!==this.transit){this.transit=!!self.transit;this.tone(self.x,self.y,.07,this.transit?240:780,.6,.12);}}
 dispose(){this.stopped=true;window.removeEventListener('pointerdown',this.unlock);window.removeEventListener('keydown',this.unlock);void this.ctx?.close();}
}
