import * as T from 'three';
import {BistroMaterials,mesh,tube,rod,torus,block,ball,batchStatic} from './materials';
import type {Transit} from '../../shared/protocol';
/** This camera is cosmetic only. Only the server removes the player's transit state. */
export class TunnelCinema {
 scene=new T.Scene();camera=new T.PerspectiveCamera(85,1,.01,18);private biomes=new Map<string,T.Group>();private lamp:T.PointLight;private progress=0;private path:T.CatmullRomCurve3;
 constructor(private m:BistroMaterials){this.scene.background=new T.Color('#17171d');this.scene.fog=new T.FogExp2('#18191e',.22);this.scene.add(new T.HemisphereLight('#b7a58e','#2d2331',1.3));this.lamp=new T.PointLight('#f3b566',2.5,4,1);this.scene.add(this.lamp);this.path=new T.CatmullRomCurve3(Array.from({length:12},(_,i)=>new T.Vector3(i*1.8,Math.sin(i*.7)*.11,Math.sin(i*.8)*.45)));for(const biome of ['pipe','roots','wood'])this.make(biome);}
 private make(biome:string){const raw=new T.Group();const wall=biome==='pipe'?this.m.get('tunnel-plaster','#605146','brick'):biome==='roots'?this.m.get('tunnel-earth','#675242','brick'):this.m.get('tunnel-wood','#755644','wood');const geo=new T.TubeGeometry(this.path,80,.27,12,false);wall.side=T.BackSide;mesh(raw,geo,wall,0,0,0);for(let i=0;i<32;i++){const t=i/33,at=this.path.getPointAt(t),tangent=this.path.getTangentAt(t);const frame=new T.Group();frame.position.copy(at);frame.quaternion.setFromUnitVectors(new T.Vector3(1,0,0),tangent);raw.add(frame);const ring=torus(frame,biome==='pipe'?this.m.copper:biome==='roots'?this.m.wood:this.m.iron,0,0,0,.265,.012);ring.rotation.y=Math.PI/2;for(let j=0;j<6;j++){const a=j*Math.PI/3;ball(frame,this.m.brass,0,Math.sin(a)*.258,Math.cos(a)*.258,.008);}if(i%4===0){block(frame,this.m.iron,-.01,.13,.22,.06,.07,.05);ball(frame,this.m.glow('tunnel-lamp','#ffc981',1.3),0,.13,.198,.017,.024,.007);if(i%8===0){const branch=tube(frame,this.m.iron,.02,-.03,-.29,.09,.14);branch.rotation.x=Math.PI/2;ball(frame,this.m.glow('mould','#7cbaa2',.8),0,.055,-.238,.024,.011,.009);}}if(biome==='roots'&&i%3===0){rod(frame,this.m.wood,new T.Vector3(0,.19,-.16),new T.Vector3(.28,.12,-.22),.011);rod(frame,this.m.wood,new T.Vector3(.1,.16,-.18),new T.Vector3(.2,.21,-.08),.006);}if(biome==='wood'&&i%3===0)rod(frame,this.m.brass,new T.Vector3(-.1,.15,-.2),new T.Vector3(.7,.12,-.22),.003);}
 const group=batchStatic(raw,false);group.visible=false;this.biomes.set(biome,group);this.scene.add(group);}
 draw(transit:Transit,time:number,dt:number,reduced:boolean,aspect:number){for(const [key,g]of this.biomes)g.visible=key===transit.biome;const fraction=Math.max(0,Math.min(.995,(time-transit.depart)/Math.max(.1,transit.arrive-transit.depart)));this.progress+=(fraction-this.progress)*Math.min(1,dt*15);if(time<transit.depart)this.progress=0;const point=this.path.getPointAt(this.progress),ahead=this.path.getPointAt(Math.min(1,this.progress+.045));this.camera.aspect=aspect;this.camera.fov=reduced?80:88+Math.sin(fraction*Math.PI)*7;this.camera.updateProjectionMatrix();this.camera.position.copy(point);if(!reduced){this.camera.position.y+=Math.sin(time*18)*.003;this.camera.position.z+=Math.sin(time*13)*.002;}this.camera.lookAt(ahead);this.lamp.position.copy(this.camera.position);this.lamp.position.y+=.07;return {scene:this.scene,camera:this.camera,progress:fraction};}
 reset(){this.progress=0;}
 dispose(){this.scene.traverse(n=>{if(n instanceof T.Mesh)n.geometry.dispose();});}
}
